// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

#include <oldEditor/de_cm.h>

enum
{
  CM_ECS_EDITOR_CREATE_ENTITY = CM_PLUGIN_BASE + 1,
  CM_ECS_EDITOR_SET_PARENT,
  CM_ECS_EDITOR_CLEAR_PARENT,
  CM_ECS_EDITOR_TOGGLE_FREE_TRANSFORM,
  CM_ECS_EDITOR_CURRENT_SCENE_TITLE,
  CM_ECS_EDITOR_CURRENT_SCENE_PATH,
  CM_ECS_EDITOR_LOAD_FROM_DEFAULT_LOCATION,
  CM_ECS_EDITOR_LOAD_FROM_CUSTOM_LOCATION,
  CM_ECS_EDITOR_RECENT_FILES_TITLE,
  CM_ECS_EDITOR_RECENT_FILE_START,                                      // inclusive
  CM_ECS_EDITOR_RECENT_FILE_END = CM_ECS_EDITOR_RECENT_FILE_START + 10, // non-inclusive
};
