#ifndef VOLMAP_GI_25D_CONSTS_INCLUDED
#define VOLMAP_GI_25D_CONSTS_INCLUDED 1

#define GI_25D_RESOLUTION_X 256
#define GI_25D_RESOLUTION_Z GI_25D_RESOLUTION_X
#define GI_25D_RESOLUTION_Y 10
#define TRACE_DIST_IN_COORD 18
#define GI_25D_RESOLUTIONU uint3(GI_25D_RESOLUTION_X, GI_25D_RESOLUTION_X, GI_25D_RESOLUTION_Y)
#define GI_25D_RESOLUTIONF float3(GI_25D_RESOLUTION_X, GI_25D_RESOLUTION_X, GI_25D_RESOLUTION_Y)

#endif