
/* A lexical analyzer generated by Dolphin */

#ifndef __LEXICAL_ANALYZER_GENERATED_BY_DOLPHIN__BLEXPARS_H

#define __LEXICAL_ANALYZER_GENERATED_BY_DOLPHIN__BLEXPARS_H

#include <iostream>

#include "base_lex.h"

class InputStream
{
public:
  virtual ~InputStream() {}
  virtual bool eof() = 0;
  virtual char get() = 0;
  virtual void stream_set(BaseLexicalAnalyzer &) = 0;
  virtual bool is_real_eof() = 0;
  virtual const char *get_filename(int file) = 0;
};

#endif // __LEXICAL_ANALYZER_GENERATED_BY_DOLPHIN__BLEXPARS_H
