// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

enum class GPUGrassTypePID
{
  NAME,
  DIFFUSE,
  NORMAL,
  VARIATIONS,
  HEIGHT,
  SIZE_LOD_MUL,
  HT_RND_ADD,
  HOR_SIZE,
  HOR_SIZE_RND_ADD,
  COLOR_MASK_R_FROM,
  COLOR_MASK_R_TO,
  COLOR_MASK_G_FROM,
  COLOR_MASK_G_TO,
  COLOR_MASK_B_FROM,
  COLOR_MASK_B_TO,
  HEIGHT_FROM_WEIGHT_MUL,
  HEIGHT_FROM_WEIGHT_ADD,
  DENSITY_FROM_WEIGHT_MUL,
  DENSITY_FROM_WEIGHT_ADD,
  VERTICAL_ANGLE_MUL,
  VERTICAL_ANGLE_ADD,

  STIFFNESS,
  HORIZONTAL_GRASS,
  UNDERWATER,

  COUNT
};