#define SP_TRACE_INDIRECT_OFFSET 0
#define SP_FILTER_INDIRECT_OFFSET 3
#define SP_IRRADIANCE_INDIRECT_OFFSET 6

#define SP_TRACE_ONLY_HISTORY_OFS 9
#define SP_TRACE_SELECTED_OFS 12
#define SP_TEMPORAL_HISTORY_OFS 15
#define SP_TEMPORAL_SELECTED_OFS 18

#define SP_INDIRECT_BUFFER_SIZE 21
