#ifndef OMM_TEXCOORD_FORMATS_HLSLI
#define OMM_TEXCOORD_FORMATS_HLSLI

#define OMM_TC_UV16_UNORM 0
#define OMM_TC_UV16_FLOAT 1
#define OMM_TC_UV32_FLOAT 2

#define OMM_TC_DAGOR_FIRST      0x100
#define OMM_TC_SHORT2_FIXED4096 0x100

#endif // OMM_TEXCOORD_FORMATS_HLSLI
