#ifndef __YUPLAY2_CALLBACK__
#define __YUPLAY2_CALLBACK__
#pragma once


#include <yuplay2_def.h>


enum Yuplay2Status
{
  YU2_OK = 0,

  YU2_BUSY,
  YU2_WRONG_PARAMETER,
  YU2_WRONG_LOGIN,
  YU2_NOT_LOGGED_IN,
  YU2_EMPTY,
  YU2_ALREADY,
  YU2_NOT_FOUND,
  YU2_FORBIDDEN,
  YU2_EXPIRED,
  YU2_NO_MONEY,
  YU2_FROZEN,
  YU2_FROZEN_BRUTEFORCE,
  YU2_NOT_OWNER,
  YU2_PROFILE_DELETED,
  YU2_PSN_UNKNOWN,
  YU2_PSN_RESTRICTED,
  YU2_NO_EULA_ACCEPTED,
  YU2_2STEP_AUTH,
  YU2_WRONG_PAYMENT,
  YU2_TENCENT_CLIENT_DLL_LOST,
  YU2_TENCENT_CLIENT_NOT_RUNNING,
  YU2_WRONG_2STEP_CODE,
  YU2_TIMEOUT,
  YU2_HOST_RESOLVE,
  YU2_SSL_CACERT,
  YU2_SSL_CACERT_FILE,
  YU2_SSL_ERROR,
  YU2_PAYMENT_LIMIT,
  YU2_BAD_DOMAIN,
  YU2_WRONG_EMAIL,
  YU2_DOI_INCOMPLETE,
  YU2_FORBIDDEN_NEED_2STEP,
  YU2_RETRY,
  YU2_UPDATE,

  YU2_UNKNOWN = 0xFFFE,
  YU2_FAIL = 0xFFFF
};


enum Yuplay2Msg
{
  YUPLAY2_CHECK_LOGIN = 1,
  YUPLAY2_USER_INFO,
  YUPLAY2_PURCHASES_COUNT,
  YUPLAY2_GAME_STATS_SET,
  YUPLAY2_USER_STATS_SET,
  YUPLAY2_USER_STATS_GET,
  YUPLAY2_GAME_DATA_GET,
  YUPLAY2_VERSION,
  YUPLAY2_YUP_FILE,
  YUPLAY2_LOCAL_VERSION,
  YUPLAY2_PURCHASE,
  YUPLAY2_RENEW_TOKEN,
  YUPLAY2_ITEM_INFO,
  YUPLAY2_MULTI_ITEM_INFO,
  YUPLAY2_MULTI_PURCHASES_COUNT,
  YUPLAY2_BASIC_USER_INFO,
  YUPLAY2_OPEN_ITEM_PAGE,
  YUPLAY2_CHECK_TOKEN,
  YUPLAY2_ACTIVATE,
  YUPLAY2_LOGGED_URL,
  YUPLAY2_PSN_LOGIN,
  YUPLAY2_GET_STOKEN,
  YUPLAY2_2STEP_LOGIN,
  YUPLAY2_TAG_USER,
  YUPLAY2_TENCENT_LOGIN,
  YUPLAY2_REMOTE_VERSION,
  YUPLAY2_STEAM_LOGIN,
  YUPLAY2_TENCENT_BUY_GOLD,
  YUPLAY2_TENCENT_PAYMENT_CONF,
  YUPLAY2_STEAM_LINK_TOKEN,
  YUPLAY2_DMM_LOGIN,
  YUPLAY2_NEWER_YUP,
  YUPLAY2_GET_TWO_STEP_CODE,
  YUPLAY2_SSO_STOKEN_LOGIN,
  YUPLAY2_XBOX_LOGIN,
  YUPLAY2_XBOX_LINK,
  YUPLAY2_SSO_LOGGED_URL,
  YUPLAY2_NSWITCH_LOGIN,
  YUPLAY2_SSO_GET_SHORT_TOKEN,
  YUPLAY2_EPIC_LOGIN,
  YUPLAY2_WEB_LOGIN_SESSION_ID,
  YUPLAY2_WEB_LOGIN,
  YUPLAY2_KONGZHONG_LOGIN,
  YUPLAY2_RENEW_JWT,
  YUPLAY2_APPLE_LOGIN,
  YUPLAY2_KONGZHONG_LOGGED_URL,
  YUPLAY2_GOOGLE_PLAY_LOGIN,
  YUPLAY2_WEGAME_LOGIN,
  YUPLAY2_FIREBASE_LOGIN,
  YUPLAY2_GOOGLE_PURCHASE,
  YUPLAY2_GUEST_LOGIN,
  YUPLAY2_FACEBOOK_LOGIN,
  YUPLAY2_APPLE_PURCHASE,
  YUPLAY2_SAMSUNG_LOGIN,
  YUPLAY2_GET_OPENID_JWT,
  YUPLAY2_EXTERNAL_LOGIN,
  YUPLAY2_HUAWEI_LOGIN,
  YUPLAY2_HUAWEI_PURCHASE,
  YUPLAY2_NVIDIA_LOGIN,
};


typedef void* Yuplay2Handle;


struct IYuplay2Cb
{
  virtual void YU2VCALL onMessage(int msg, Yuplay2Handle req, int status, const void* data) = 0;
};


struct Yuplay2AsyncCall
{
  IYuplay2Cb* cb;
  Yuplay2Handle handle;
};


#if YU2_LIBRARY_DLL
extern "C"
{
#endif //YU2_LIBRARY_DLL

YU2DLL const char* YU2CALL yuplay2_status_string(int status, bool brief=false);

#if YU2_LIBRARY_DLL
}
#endif //YU2_LIBRARY_DLL


#endif //__YUPLAY2_CALLBACK__
