DAG_ID = 0x1A474144
DAG_END = 0
DAG_NODE = 1
DAG_MATER = 2
DAG_TEXTURES = 3
DAG_KEYLABELS = 4
DAG_NOTETRACK = 5


DAG_NODE_TM = 1
DAG_NODE_DATA = 2
DAG_NODE_SCRIPT = 3
DAG_NODE_OBJ = 4
DAG_NODE_MATER = 5
DAG_NODE_ANIM = 6
DAG_NODE_CHILDREN = 7
DAG_NODE_NOTETRACK = 8


DAG_OBJ_MESH = 1
DAG_OBJ_BIGMESH = 2
DAG_OBJ_LIGHT = 3
DAG_OBJ_BONES = 4
DAG_OBJ_SPLINES = 5
DAG_OBJ_FACEFLG = 6
DAG_OBJ_NORMALS = 7


DAG_NF_RENDERABLE = 1
DAG_NF_CASTSHADOW = 2
DAG_NF_RCVSHADOW = 4


DAGTEXNUM = 16
DAGBADMATID = 0xFFFF

DAG_MF_16TEX = 0x80000000

DAG_SKNOT_BEZIER = 1

DAG_FACEFLG_EDGE0 = 1
DAG_FACEFLG_EDGE1 = 2
DAG_FACEFLG_EDGE2 = 4
DAG_FACEFLG_HIDDEN = 8

NUMMESHTCH = 10

DAG_MF_2SIDED = 1