//
// Dagor Engine 6.5
// Copyright (C) Gaijin Games KFT.  All rights reserved.
//
#pragma once

#include <generic/dag_carray.h>

namespace HumanInput
{
enum
{
  JOY_XINPUT_REAL_NONE = -1,

  // XBOX360 gamepad button indices
  JOY_XINPUT_REAL_BTN_D_UP = 0,
  JOY_XINPUT_REAL_BTN_D_DOWN = 1,
  JOY_XINPUT_REAL_BTN_D_LEFT = 2,
  JOY_XINPUT_REAL_BTN_D_RIGHT = 3,
  JOY_XINPUT_REAL_BTN_START = 4,
  JOY_XINPUT_REAL_BTN_BACK = 5,
  JOY_XINPUT_REAL_BTN_L_THUMB = 6,
  JOY_XINPUT_REAL_BTN_R_THUMB = 7,
  JOY_XINPUT_REAL_BTN_L_SHOULDER = 8,
  JOY_XINPUT_REAL_BTN_R_SHOULDER = 9,
  JOY_XINPUT_REAL_BTN_0X0400 = 10,
  JOY_XINPUT_REAL_BTN_0X0800 = 11,
  JOY_XINPUT_REAL_BTN_A = 12,
  JOY_XINPUT_REAL_BTN_B = 13,
  JOY_XINPUT_REAL_BTN_X = 14,
  JOY_XINPUT_REAL_BTN_Y = 15,
  JOY_XINPUT_REAL_BTN_L_TRIGGER = 16,
  JOY_XINPUT_REAL_BTN_R_TRIGGER = 17,
  JOY_XINPUT_REAL_BTN_L_THUMB_RIGHT = 18,
  JOY_XINPUT_REAL_BTN_L_THUMB_LEFT = 19,
  JOY_XINPUT_REAL_BTN_L_THUMB_UP = 20,
  JOY_XINPUT_REAL_BTN_L_THUMB_DOWN = 21,
  JOY_XINPUT_REAL_BTN_R_THUMB_RIGHT = 22,
  JOY_XINPUT_REAL_BTN_R_THUMB_LEFT = 23,
  JOY_XINPUT_REAL_BTN_R_THUMB_UP = 24,
  JOY_XINPUT_REAL_BTN_R_THUMB_DOWN = 25,
  _JOY_XINPUT_LEGACY_L_THUMB_CENTER = 26,
  _JOY_XINPUT_LEGACY_R_THUMB_CENTER = 27,

  JOY_XINPUT_REAL_BTN_COUNT
};

enum
{
  // XBOX360 gamepad button bits masks
  JOY_XINPUT_REAL_MASK_D_UP = 0x00000001,
  JOY_XINPUT_REAL_MASK_D_DOWN = 0x00000002,
  JOY_XINPUT_REAL_MASK_D_LEFT = 0x00000004,
  JOY_XINPUT_REAL_MASK_D_RIGHT = 0x00000008,
  JOY_XINPUT_REAL_MASK_START = 0x00000010,
  JOY_XINPUT_REAL_MASK_BACK = 0x00000020,
  JOY_XINPUT_REAL_MASK_L_THUMB = 0x00000040,
  JOY_XINPUT_REAL_MASK_R_THUMB = 0x00000080,
  JOY_XINPUT_REAL_MASK_L_SHOULDER = 0x00000100,
  JOY_XINPUT_REAL_MASK_R_SHOULDER = 0x00000200,
  JOY_XINPUT_REAL_MASK_0X0400 = 0x00000400,
  JOY_XINPUT_REAL_MASK_0X0800 = 0x00000800,
  JOY_XINPUT_REAL_MASK_A = 0x00001000,
  JOY_XINPUT_REAL_MASK_B = 0x00002000,
  JOY_XINPUT_REAL_MASK_X = 0x00004000,
  JOY_XINPUT_REAL_MASK_Y = 0x00008000,
  JOY_XINPUT_REAL_MASK_L_TRIGGER = 0x00010000,
  JOY_XINPUT_REAL_MASK_R_TRIGGER = 0x00020000,
  JOY_XINPUT_REAL_MASK_L_THUMB_RIGHT = 0x00040000,
  JOY_XINPUT_REAL_MASK_L_THUMB_LEFT = 0x00080000,
  JOY_XINPUT_REAL_MASK_L_THUMB_UP = 0x00100000,
  JOY_XINPUT_REAL_MASK_L_THUMB_DOWN = 0x00200000,
  JOY_XINPUT_REAL_MASK_R_THUMB_RIGHT = 0x00400000,
  JOY_XINPUT_REAL_MASK_R_THUMB_LEFT = 0x00800000,
  JOY_XINPUT_REAL_MASK_R_THUMB_UP = 0x01000000,
  JOY_XINPUT_REAL_MASK_R_THUMB_DOWN = 0x02000000,
  _JOY_XINPUT_LEGACY_MASK_L_THUMB_CENTER = 0x04000000,
  _JOY_XINPUT_LEGACY_MASK_R_THUMB_CENTER = 0x08000000,
};

enum
{
  JOY_XINPUT_REAL_AXIS_L_THUMB_H = 0,
  JOY_XINPUT_REAL_AXIS_L_THUMB_V = 1,
  JOY_XINPUT_REAL_AXIS_R_THUMB_H = 2,
  JOY_XINPUT_REAL_AXIS_R_THUMB_V = 3,
  JOY_XINPUT_REAL_AXIS_L_TRIGGER = 4,
  JOY_XINPUT_REAL_AXIS_R_TRIGGER = 5,
  JOY_XINPUT_REAL_AXIS_LR_TRIGGER = 6,

  JOY_XINPUT_REAL_AXIS_COUNT
};

static carray<const char *, JOY_XINPUT_REAL_BTN_COUNT> joyXInputButtonName = {"D.Up", "D.Down", "D.Left", "D.Right",
#if _TARGET_XBOX
  "Menu", "View", "LS", "RS", "LB", "RB", "", "", "A", "B", "X", "Y", "LT", "RT",
#else
  "Start", "Select", "L3", "R3", "L1", "R1", "0x0400", "0x0800", "CROSS", "CIRCLE", "SQUARE", "TRIANGLE", "L2", "R2",
#endif
  "LS.Right", "LS.Left", "LS.Up", "LS.Down", "RS.Right", "RS.Left", "RS.Up", "RS.Down",
#if _TARGET_XBOX
  "LS.Centered", "RS.Centered"
#else
  "L3.Centered", "R3.Centered"
#endif
};

static carray<const char *, JOY_XINPUT_REAL_AXIS_COUNT> joyXInputAxisName = {
  "L.Thumb.h", "L.Thumb.v", "R.Thumb.h", "R.Thumb.v", "L.Trigger", "R.Trigger", "R+L.Trigger"};

static constexpr int JOY_XINPUT_MIN_AXIS_VAL = -32000;
static constexpr int JOY_XINPUT_MAX_AXIS_VAL = 32000;

} // namespace HumanInput
