// Copyright 2024 Google LLC
// SPDX-License-Identifier: Apache-2.0
//
// This file is auto-generated by CMake during the official build.
// For Jam/other builds, this pre-configured version provides feature definitions.

#ifndef DRACO_CORE_DRACO_FEATURES_H_
#define DRACO_CORE_DRACO_FEATURES_H_

// Core feature flags - required for assimp integration
#define DRACO_MESH_COMPRESSION_SUPPORTED 1
#define DRACO_POINT_CLOUD_COMPRESSION_SUPPORTED 1

// Version information
#define DRACO_VERSION_MAJOR 1
#define DRACO_VERSION_MINOR 5
#define DRACO_VERSION_PATCH 7

// Encoder/Decoder flags
#define DRACO_ENABLE_ENCODER 1
#define DRACO_ENABLE_DECODER 1

// Compression scheme support
#define DRACO_MESH_COMPRESSION 1
#define DRACO_ANIMATION_COMPRESSION 1

// Attribute compression settings
#define DRACO_ATTRIBUTE_COMPRESSION 1
#define DRACO_ATTRIBUTE_QUANTIZATION 1
#define DRACO_NORMAL_COMPRESSION 1
#define DRACO_NORMAL_ENCODING_SUPPORTED 1
#define DRACO_TEXTURE_COORDINATE_COMPRESSION 1
#define DRACO_COLORS_COMPRESSION 1
#define DRACO_JOINTS_WEIGHTS_COMPRESSION 1

// Prediction scheme support
#define DRACO_MESH_PREDICTION_SCHEMES 1
#define DRACO_POINT_CLOUD_PREDICTION_SCHEMES 1

// Decoding optimization flags
#define DRACO_SEQUENTIAL_DECODING 1
#define DRACO_EDGEBREAKER_DECODING 1
#define DRACO_KD_TREE_DECODING 1

// Platform detection
#if defined(_WIN32) || defined(_WIN64)
#define DRACO_PLATFORM_WINDOWS 1
#elif defined(__APPLE__)
#define DRACO_PLATFORM_MAC 1
#elif defined(__linux__)
#define DRACO_PLATFORM_LINUX 1
#endif

#endif  // DRACO_CORE_DRACO_FEATURES_H_
