#pragma once
#include <generic/dag_tab.h>
#include <generic/dag_staticTab.h>
#include "descriptor_set.h"
#include "render_pass.h"
#include "pipeline/base_pipeline.h"
#include "pipeline/main_pipelines.h"
#include "raytrace/pipeline.h"
#include "pipeline/variated_graphics.h"
#include "pipeline/manager.h"
#include "pipeline/stage_state_base.h"
