#ifndef __GAIJIN_EDITORCORE_EC_CM_H__
#define __GAIJIN_EDITORCORE_EC_CM_H__
#pragma once

enum EditorCoreCM
{
  // menu items
  CM_FILE = 99,
  CM_FILE_NEW,
  CM_FILE_OPEN,
  CM_FILE_SAVE,

  CM_FILE_RECENT_BASE,
  CM_FILE_RECENT_LAST = CM_FILE_RECENT_BASE + 20,

  CM_VIEWPORT_LAYOUT_4,
  CM_VIEWPORT_LAYOUT_2HOR,
  CM_VIEWPORT_LAYOUT_2VERT,
  CM_VIEWPORT_LAYOUT_1,

  CM_VIEW,
  CM_VIEW_PERSPECTIVE,
  CM_VIEW_FRONT,
  CM_VIEW_BACK,
  CM_VIEW_TOP,
  CM_VIEW_BOTTOM,
  CM_VIEW_LEFT,
  CM_VIEW_RIGHT,
  CM_VIEW_CUSTOM_ORTHOGONAL,
  CM_VIEW_CUSTOM_CAMERA,
  CM_VIEW_WIREFRAME,
  CM_VIEW_EDGED,
  CM_VIEW_GRID_SHOW,
  CM_VIEW_GRID_INC_STEP,
  CM_VIEW_GRID_DEC_STEP,
  CM_VIEW_GRID_MOVE_SNAP,
  CM_VIEW_GRID_ANGLE_SNAP,
  CM_VIEW_GRID_SCALE_SNAP,
  CM_VIEW_SHOW_STATS,
  CM_VIEW_STAT3D_OPAQUE,
  CM_VIEW_STAT3D_COLOR_HISTORGAM,
  CM_VIEW_STAT3D_BRIGHTNESS_HISTORGAM,

  CM_GROUP_GRID,
  CM_GROUP_CLIPPING,

  CM_CAMERAS_FREE,
  CM_CAMERAS_FPS,
  CM_CAMERAS_TPS,
  CM_CAMERAS_CAR,
  CM_CAMERA_MOVE,

  CM_PLUGIN_FIRST_CAMERA,
  CM_PLUGIN_LAST_CAMERA = CM_PLUGIN_FIRST_CAMERA + 200,

  CM_OPTIONS,
  CM_OPTIONS_CAMERAS,
  CM_OPTIONS_GRID,
  CM_OPTIONS_SCREENSHOT,
  CM_OPTIONS_STAT_DISPLAY_SETTINGS,

  CM_TOOLS,
  CM_CREATE_SCREENSHOT,
  CM_CREATE_CUBE_SCREENSHOT,
  CM_CREATE_ORTHOGONAL_SCREENSHOT,

  CM_EXIT,

  CM_EDIT,
  CM_UNDO,
  CM_REDO,
  CM_SELECT_ALL,
  CM_DESELECT_ALL,

  CM_GIZMO_X,
  CM_GIZMO_Y,
  CM_GIZMO_Z,
  CM_GIZMO_BASIS,
  CM_GIZMO_CENTER,

  CM_ROTATE_CENTER_AND_OBJ,

  CM_ZOOM_AND_CENTER,
  CM_NAVIGATE,
  CM_STATS,
  CM_CHANGE_VIEWPORT,
  CM_CHANGE_FOV,
  CM_ENVIRONMENT_SETTINGS,
  CM_CONSOLE,
  CM_PALETTE,

  CM_STATS_SETTINGS_TAB_PANEL,
  CM_STATS_SETTINGS_MAIN_PAGE,
  CM_STATS_SETTINGS_MAIN_SHOW_STAT3D_STATS,
  CM_STATS_SETTINGS_MAIN_SHOW_CAMERA_STATS,
  CM_STATS_SETTINGS_STAT3D_PAGE,
  CM_STATS_SETTINGS_STAT3D_ITEM0,
  CM_STATS_SETTINGS_STAT3D_ITEM_LAST = CM_STATS_SETTINGS_STAT3D_ITEM0 + 100,
  CM_STATS_SETTINGS_CAMERA_PAGE,
  CM_STATS_SETTINGS_CAMERA_POS,
  CM_STATS_SETTINGS_CAMERA_DIST,
  CM_STATS_SETTINGS_CAMERA_FOV,
  CM_STATS_SETTINGS_CAMERA_SPEED,
  CM_STATS_SETTINGS_CAMERA_TURBO_SPEED,

  // ObjectEditor commands. Put it between CM_OBJED_FIRST and CM_OBJED_LAST enum keys.
  CM_OBJED_FIRST,

  CM_OBJED_MODE_SELECT,
  CM_OBJED_MODE_MOVE,
  CM_OBJED_MODE_SURF_MOVE,
  CM_OBJED_MODE_ROTATE,
  CM_OBJED_MODE_SCALE,

  CM_OBJED_DROP,
  CM_OBJED_OBJPROP_PANEL,
  CM_OBJED_SELECT_BY_NAME,
  CM_OBJED_SELECT_FILTER,

  CM_OBJED_DELETE,

  CM_OBJED_LAST,

  CM_SAVE_ACTIVE_VIEW,
  CM_RESTORE_ACTIVE_VIEW,

  CM_SET_VIEWPORT_CLIPPING,
  CM_SET_DEFAULT_VIEWPORT_CLIPPING,

  CM__LAST_USED_BY_CORE
};

#endif
