#pragma once

#include <sepGui/wndCommon.h>


#ifndef WS_EX_LAYERED
#define WS_EX_LAYERED 0x00080000
#endif
#define LWA_ALPHA 0x00000002


const int SPR_DELETE = 10;
const int SPR_HOLD = 11;

const int MENU_ITEM_NAME_SIZE = 100;

const int MAIN_CLIENT_AREA_OFFSET = 2;

enum
{
  WINDOW_MENU_AREA_X = 0,
  WINDOW_MENU_AREA_Y = 0,
  WINDOW_MENU_AREA_W = 20,
  WINDOW_MENU_AREA_H = 15,
};

enum
{
  SPLITTER_THICKNESS = 3,
  SPLITTER_SPACE = 1,
  DISTANCE_TO_BORDER = 5,

  WINDOW_MIN_SIZE_H = 23,
  WINDOW_MIN_SIZE_W = 23,
  WINDOW_TEMP_MIN_SIZE = 10,
  WINDOW_AREA_SIZE_TO_MAKE_UNMOVABLE = 40,
  WINDOW_AREA_SIZE_TO_MAKE_UNMOVABLE_TO_ROOT = 50,
};

const int ALIGN_ROOT_WINDOWS_DEFAULT_ALPHA = 150;
const int ALIGN_ROOT_WINDOWS_FOCUS_ALPHA = 220;
const int ALIGN_WINDOWS_ALPHA = 192;
