// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

#include <drv/hid/dag_hiKeybIds.h>

namespace HumanInput
{
struct GameInputKeyName
{
  int hid_id;
  const char *name;
};

static const GameInputKeyName gameinput_key_names[] = {
  {DKEY_ESCAPE, "Esc"},
  {DKEY_1, "1"},
  {DKEY_2, "2"},
  {DKEY_3, "3"},
  {DKEY_4, "4"},
  {DKEY_5, "5"},
  {DKEY_6, "6"},
  {DKEY_7, "7"},
  {DKEY_8, "8"},
  {DKEY_9, "9"},
  {DKEY_0, "0"},
  {DKEY_MINUS, "-"},
  {DKEY_EQUALS, "="},
  {DKEY_BACK, "Backspace"},
  {DKEY_TAB, "Tab"},
  {DKEY_Q, "Q"},
  {DKEY_W, "W"},
  {DKEY_E, "E"},
  {DKEY_R, "R"},
  {DKEY_T, "T"},
  {DKEY_Y, "Y"},
  {DKEY_U, "U"},
  {DKEY_I, "I"},
  {DKEY_O, "O"},
  {DKEY_P, "P"},
  {DKEY_LBRACKET, "["},
  {DKEY_RBRACKET, "]"},
  {DKEY_RETURN, "Enter"},
  {DKEY_LCONTROL, "Ctrl"},
  {DKEY_A, "A"},
  {DKEY_S, "S"},
  {DKEY_D, "D"},
  {DKEY_F, "F"},
  {DKEY_G, "G"},
  {DKEY_H, "H"},
  {DKEY_J, "J"},
  {DKEY_K, "K"},
  {DKEY_L, "L"},
  {DKEY_SEMICOLON, ";"},
  {DKEY_APOSTROPHE, "'"},
  {DKEY_GRAVE, "`"},
  {DKEY_LSHIFT, "Shift"},
  {DKEY_BACKSLASH, "\\"},
  {DKEY_Z, "Z"},
  {DKEY_X, "X"},
  {DKEY_C, "C"},
  {DKEY_V, "V"},
  {DKEY_B, "B"},
  {DKEY_N, "N"},
  {DKEY_M, "M"},
  {DKEY_COMMA, ","},
  {DKEY_PERIOD, "."},
  {DKEY_SLASH, "/"},
  {DKEY_RSHIFT, "Right Shift"},
  {DKEY_MULTIPLY, "Num *"},
  {DKEY_LALT, "Alt"},
  {DKEY_SPACE, "Space"},
  {DKEY_CAPITAL, "Caps Lock"},
  {DKEY_F1, "F1"},
  {DKEY_F2, "F2"},
  {DKEY_F3, "F3"},
  {DKEY_F4, "F4"},
  {DKEY_F5, "F5"},
  {DKEY_F6, "F6"},
  {DKEY_F7, "F7"},
  {DKEY_F8, "F8"},
  {DKEY_F9, "F9"},
  {DKEY_F10, "F10"},
  {DKEY_NUMLOCK, "Num Lock"},
  {DKEY_SCROLL, "Scroll Lock"},
  {DKEY_NUMPAD7, "Num 7"},
  {DKEY_NUMPAD8, "Num 8"},
  {DKEY_NUMPAD9, "Num 9"},
  {DKEY_SUBTRACT, "Num -"},
  {DKEY_NUMPAD4, "Num 4"},
  {DKEY_NUMPAD5, "Num 5"},
  {DKEY_NUMPAD6, "Num 6"},
  {DKEY_ADD, "Num +"},
  {DKEY_NUMPAD1, "Num 1"},
  {DKEY_NUMPAD2, "Num 2"},
  {DKEY_NUMPAD3, "Num 3"},
  {DKEY_NUMPAD0, "Num 0"},
  {DKEY_DECIMAL, "Num Del"},
  {DKEY_OEM_102, "\\"},
  {DKEY_F11, "F11"},
  {DKEY_F12, "F12"},
  {DKEY_F13, "F13"},
  {DKEY_F14, "F14"},
  {DKEY_F15, "F15"},
  {DKEY_KANA, "KANA"},
  {DKEY_ABNT_C1, "ABNT_C1"},
  {DKEY_CONVERT, "CONV"},
  {DKEY_NOCONVERT, "NOCONV"},
  {DKEY_YEN, "YEN"},
  {DKEY_ABNT_C2, "ABNT_C2"},
  {DKEY_NUMPADEQUALS, "="},
  {DKEY_PREVTRACK, "Q"},
  {DKEY_AT, "W"},
  {DKEY_COLON, "E"},
  {DKEY_UNDERLINE, "R"},
  {DKEY_KANJI, "T"},
  {DKEY_STOP, "Y"},
  {DKEY_AX, "U"},
  {DKEY_UNLABELED, "I"},
  {DKEY_NEXTTRACK, "P"},
  {DKEY_NUMPADENTER, "Num Enter"},
  {DKEY_RCONTROL, "Right Ctrl"},
  {DKEY_MUTE, "D"},
  {DKEY_CALCULATOR, "F"},
  {DKEY_PLAYPAUSE, "G"},
  {DKEY_MEDIASTOP, "J"},
  {DKEY_VOLUMEDOWN, "C"},
  {DKEY_VOLUMEUP, "B"},
  {DKEY_WEBHOME, "M"},
  {DKEY_NUMPADCOMMA, ","},
  {DKEY_DIVIDE, "Num /"},
  {DKEY_SYSRQ, "Prnt Scrn"},
  {DKEY_RALT, "Right Alt"},
  {DKEY_PAUSE, "Pause"},
  {DKEY_HOME, "Home"},
  {DKEY_UP, "Up"},
  {DKEY_PRIOR, "Page Up"},
  {DKEY_LEFT, "Left"},
  {DKEY_RIGHT, "Right"},
  {DKEY_END, "End"},
  {DKEY_DOWN, "Down"},
  {DKEY_NEXT, "Page Down"},
  {DKEY_INSERT, "Insert"},
  {DKEY_DELETE, "Delete"},
  {DKEY_LWIN, "Left Windows"},
  {DKEY_RWIN, "Right Windows"},
  {DKEY_APPS, "Application"},
  {DKEY_POWER, "Pwr"},
  {DKEY_SLEEP, "Sleep"},
  {DKEY_WAKE, "Wake"},
};
} // namespace HumanInput
