//
// Dagor Engine 6.5
// Copyright (C) Gaijin Games KFT.  All rights reserved.
//
#pragma once

/*
 * Before adding a new TAG, consider using one that already exist, otherwise the
 * memory report will be overly fragmented and be less useful.
 */

#define RESTAG_VR                   "VR"
#define RESTAG_ATLAS                "atlas"
#define RESTAG_RINGDYNBUF           "ringDynBuf"
#define RESTAG_AVIWRITER            "aviWriter"
#define RESTAG_DDSX_TEX             "ddsx_tex"
#define RESTAG_STAGING              "staging"
#define RESTAG_DDS_TEXTURE          "dds_texture"
#define RESTAG_GUI                  "gui"
#define RESTAG_IMGUI                "imgui"
#define RESTAG_DEBUG                "debug"
#define RESTAG_OCCLUSION            "occlusion"
#define RESTAG_QUAD_INDEX_BUFFER    "quadIndexBuffer"
#define RESTAG_REGTEX               "reg_tex"
#define RESTAG_RESIZABLE_TEX        "resizable_tex"
#define RESTAG_RING_CPU_BUFFER_LOCK "RingCPUBufferLock"
#define RESTAG_SERIAL_INT_BUFFER    "serialIntBuffer"
#define RESTAG_PERFMON              "perfMon"
#define RESTAG_RENDINST             "rendInst"
#define RESTAG_DIFFUSE_MIPMAP       "diffuse_mipmap"
#define RESTAG_SHADER_MESH          "shaderMesh"
#define RESTAG_VIDEO                "video"
#define RESTAG_APEX                 "apex"
#define RESTAG_BVH                  "bvh"
#define RESTAG_DAGI                 "daGI"
#define RESTAG_DAGI2                "daGI2"
#define RESTAG_DASDF                "daSDF"
#define RESTAG_DASKIES2             "daSkies2"
#define RESTAG_WATER                "water"
#define RESTAG_LAND                 "land"
#define RESTAG_PHYSMAP              "physMap"
#define RESTAG_DASRES               "dasRes"
#define RESTAG_VOLTEX_RENDERER      "voltexRenderer"
#define RESTAG_RESOURCE_POOL        "resourcePool"
#define RESTAG_AA                   "aa"
#define RESTAG_TARGET               "target"
#define RESTAG_SHADOW               "shadow"
#define RESTAG_LIGHTS               "lights"
#define RESTAG_FRAMEGRAPH           "frameGraph"
#define RESTAG_DENOISER             "denoiser"
#define RESTAG_AO                   "ao"
#define RESTAG_SSR                  "ssr"
#define RESTAG_FX                   "fx"
#define RESTAG_DOF                  "dof"
#define RESTAG_GRASS                "grass"
#define RESTAG_POSTFX               "postfx"
#define RESTAG_BENCHMARK            "benchmark"
#define RESTAG_HDR                  "hdr"
#define RESTAG_WETNESS              "wetness"
#define RESTAG_LENSFLARE            "lensflare"
#define RESTAG_NOISE                "noise"
#define RESTAG_MOTIONBLUR           "motionblur"
#define RESTAG_PARTIAL_DXT          "partial_dxt"
#define RESTAG_RAIN                 "rain"
#define RESTAG_RTR                  "rtr"
#define RESTAG_SHADER_CAHCE         "shader_cache"
#define RESTAG_COMPRESS             "compress"
#define RESTAG_TRACER               "tracer"
#define RESTAG_TREES2D              "trees2d"
#define RESTAG_VOLFOG               "volfog"
#define RESTAG_VOXEL                "voxel"
#define RESTAG_WIND                 "wind"
#define RESTAG_XRAY                 "xray"
#define RESTAG_ALIASABLE            "aliasable"
#define RESTAG_TEXGEN               "tex_gen"
#define RESTAG_CABLE                "cable"
#define RESTAG_ENVIRONMENT_ANALYZER "EnvironmentAnalyzer"
#define RESTAG_EXPLOSION_PATCH      "explosionPatch"
#define RESTAG_TRACK                "track"
#define RESTAG_VAPOR                "vapor"
#define RESTAG_WT                   "wt"
#define RESTAG_SCREENSHOT           "screenshot"
#define RESTAG_AFTERBURNER          "afterburner"
#define RESTAG_DYNDEFORM            "dynDeform"
#define RESTAG_NIGHTVISION          "night_vision"
#define RESTAG_NUKE                 "nuke"
#define RESTAG_SONAR                "sonar"
#define RESTAG_SSSS                 "ssss"
#define RESTAG_ENVI_COVER           "envi_cover"
#define RESTAG_ROCKET_WIRE          "rocket_wire"
#define RESTAG_FARAWAY_RENDER       "farawayRender"
#define RESTAG_TACVIEW              "tacView"
#define RESTAG_ENGINE               "3dengine"
#define RESTAG_UNITED_DATA          "unitedData"
#define RESTAG_DASWRT               "daSWRT"
#define RESTAG_GPUOBJ               "gpuObject"
#define RESTAG_DECALS               "decals"
#define RESTAG_COLLISION            "collision"
#define RESTAG_INDOOR_PROBES        "indoorProbes"
#define RESTAG_DYNMODEL             "dynModel"
