#ifndef DAFX_QUALITY_FLAGS_HLSLI
#define DAFX_QUALITY_FLAGS_HLSLI

#define DAFX_LOW_FX_QUALITY ( 1 << 0 )
#define DAFX_MEDIUM_FX_QUALITY ( 1 << 1 )
#define DAFX_HIGH_FX_QUALITY ( 1 << 2 )

#endif // DAFX_QUALITY_FLAGS_HLSLI