set CSQEXE=..\..\..\tools\dagor3_cdk\util\csq-dev.exe
%CSQEXE% StdEmitter.gen.nut 
%CSQEXE% StaticVisSphere.gen.nut
%CSQEXE% StdFxShaderParams.gen.nut
%CSQEXE% CompoundPs.gen.nut 
%CSQEXE% FlowPs2.gen.nut 
%CSQEXE% lightFx.gen.nut
%CSQEXE% dafxEmitter.gen.nut
%CSQEXE% dafxSparks.gen.nut
%CSQEXE% dafxModfx.gen.nut
%CSQEXE% dafxCompound.gen.nut
