#ifndef RENDER_LIGHTS_CONSTS_INCLUDED
#define RENDER_LIGHTS_CONSTS_INCLUDED

#define TEX_ID_MULTIPLIER (1 << 5)

#define MAX_CLUSTERED_SPOT_LIGHTS 256
#define MAX_CLUSTERED_OMNI_LIGHTS 256

#define MAX_SCENE_OMNI_LIGHTS 2048
#define MAX_SCENE_SPOT_LIGHTS 2048

#ifndef M_PI
#define M_PI 3.1415926536
#endif

#define IES_TEX_ID_TYPE_BIT_OFFSET 1
#define IES_TEX_ID_TYPE_BIT_MASK 1 // 0b1
#define IES_TEX_ID_TYPE__IES 0 // 0b0
#define IES_TEX_ID_TYPE__PROJ 1 // 0b1

#define USE_OCTAHEDRAL_MAPPING 1

#define SPOT_LIGHT_ROLL_BIT_OFFSET 2
#define SPOT_LIGHT_ROLL_BIT_COUNT 11
#define SPOT_LIGHT_ROLL_MAX_VALUE ((1<<SPOT_LIGHT_ROLL_BIT_COUNT) - 1)
#define SPOT_LIGHT_ROLL_MASK (SPOT_LIGHT_ROLL_MAX_VALUE << SPOT_LIGHT_ROLL_BIT_OFFSET)

#define SPOT_LIGHT_CONTACT_SHADOW_MASK (0x03)

#endif