MODE(diffuseColor, 1)
MODE(specularColor, 2)
MODE_HAS_VECTORS(normal, 3)
MODE(smoothness, 4)
MODE(baseColor, 5)
MODE(metalness, 6)
MODE(materialType, 7)
MODE(ssao, 8)
MODE(ao, 9)
MODE(albedo_ao, 10)
MODE(finalAO, 11)
MODE(preshadow, 12)
MODE(translucency, 13)
MODE(depth, 14)
MODE(ssr, 15)
MODE(ssrStrength, 16)
MODE(reflectance, 17)
MODE(emission, 18)
MODE(wsao, 19)
MODE(lights, 20)
MODE(motionGbuf, 21)
MODE(motionResolvedXY, 22)
MODE(motionResolvedDepth, 23)
MODE(isHeroCockpit, 24)
MODE(mip, 25)
MODE(texelDensity, 26)
MODE(impostorMask, 27)
// must always be the last
LAST_MODE(debug_mesh)
DEBUG_MESH_MODE(lod)
DEBUG_MESH_MODE(drawElements)
DEBUG_MESH_MODE(overdraw)
