#ifndef RENDER_LIGHTS_CONSTS_INCLUDED
#define RENDER_LIGHTS_CONSTS_INCLUDED

#define TEX_ID_MULTIPLIER (1 << 5)

#define MAX_SPOT_LIGHTS 256
#define MAX_OMNI_LIGHTS 256

#ifndef M_PI
#define M_PI 3.1415926536
#endif

#define USE_OCTAHEDRAL_MAPPING 1

#endif