#ifndef __RIEXTRA_PER_INSTANCE_HLSLI__
#define __RIEXTRA_PER_INSTANCE_HLSLI__

// Encoded data format used in riExtra buffer:
//  <optional flags> | <data flags> | <additional data buffer offset: index in float4 array>

#define RIEXTRA_PER_INSTANCE_RENDER_DATA_FLAG_BIT_COUNT 4
#define RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_COUNT 1

#define RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_OFFSET (32-RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_COUNT)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA_FLAG_BIT_OFFSET (32-RIEXTRA_PER_INSTANCE_RENDER_DATA_FLAG_BIT_COUNT-RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_COUNT)

#define RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_MASK (0xffffffffu << RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_OFFSET)
#define RIEXTRA_PER_INSTANCE_RENDER_OFFSET_MASK (0xffffffffu >> (RIEXTRA_PER_INSTANCE_RENDER_DATA_FLAG_BIT_COUNT+RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_BIT_COUNT))
#define RIEXTRA_PER_INSTANCE_RENDER_DATA_FLAG_MASK (~(RIEXTRA_PER_INSTANCE_RENDER_OPTIONAL_FLAG_MASK|RIEXTRA_PER_INSTANCE_RENDER_OFFSET_MASK))

#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__FLAG (1<<0)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__FLAG (1<<1)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__PREV_TRANSFORM__FLAG (1<<2)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__DESTR_RENDER_DATA__FLAG (1<<3)

// Size = number of float4 slots used
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__SIZE (1)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__SIZE (3)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__PREV_TRANSFORM__SIZE (4)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__DESTR_RENDER_DATA__SIZE (2)

#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__OFFSET(flags) 0
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__OFFSET(flags) \
  (((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__SIZE : 0)
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__PREV_TRANSFORM__OFFSET(flags) \
  ((((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__SIZE : 0) + \
  (((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__SIZE : 0))
#define RIEXTRA_PER_INSTANCE_RENDER_DATA__DESTR_RENDER_DATA__OFFSET(flags) \
  ((((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_POS__SIZE : 0) + \
  (((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__INITIAL_TM_3X3__SIZE : 0) + \
  (((flags)&RIEXTRA_PER_INSTANCE_RENDER_DATA__PREV_TRANSFORM__FLAG) ? RIEXTRA_PER_INSTANCE_RENDER_DATA__PREV_TRANSFORM__SIZE : 0))

#endif