#ifndef SPOT_LIGHT_SHADOW_FLAGS_HLSL
#define SPOT_LIGHT_SHADOW_FLAGS_HLSL

#define SPOT_LIGHT_HAS_SHADOW_FLAG 0
#define SPOT_LIGHT_NEEDS_CONTACT_SHADOWS_FLAG 1

#define SPOT_LIGHT_HAS_SHADOW_MASK (1 << SPOT_LIGHT_HAS_SHADOW_FLAG)
#define SPOT_LIGHT_NEEDS_CONTACT_SHADOWS_MASK (1 << SPOT_LIGHT_NEEDS_CONTACT_SHADOWS_FLAG)

#endif // SPOT_LIGHT_SHADOW_FLAGS_HLSL