//#include "LinearMath/btAlignedAllocator.cpp" //Note: this module is intentionally not used, memory routines provided by dagor engine
#include "LinearMath/btGeometryUtil.cpp"
#include "LinearMath/btSerializer.cpp"
#include "LinearMath/btVector3.cpp"
#include "LinearMath/btConvexHull.cpp"
#include "LinearMath/btPolarDecomposition.cpp"
#include "LinearMath/btSerializer64.cpp"
#include "LinearMath/btConvexHullComputer.cpp"
#include "LinearMath/btQuickprof.cpp"
#include "LinearMath/btThreads.cpp"
#include "LinearMath/btReducedVector.cpp"
#include "LinearMath/TaskScheduler/btTaskScheduler.cpp"
#include "LinearMath/TaskScheduler/btThreadSupportPosix.cpp"
#include "LinearMath/TaskScheduler/btThreadSupportWin32.cpp"

