//
// Dagor Engine 6.5 - Game Libraries
// Copyright (C) Gaijin Games KFT.  All rights reserved.
//
#pragma once

#include <sepClient/details/commonTypes.h>
#include <sepClient/details/urlSelector.h>
#include <sepClient/reconnectDelayConfig.h>

#include <websocketJsonRpc/wsJsonRpcConnection.h>


namespace sepclient
{
struct SepClientConfig;
}


namespace sepclient::details
{

class ConnectionConfigGenerator final
{
public:
  explicit ConnectionConfigGenerator(const SepClientConfig &config);

  bool updateAuthorizationToken(eastl::string_view new_authorization_token);

  bool resetAuthorizationTokenIfTheSame(eastl::string_view previous_authorization_token);

  bool haveEnoughConnectionParams() const;

  // Returns nullptr if there is not enough information to connect
  // or if additional delay is needed before next connect
  websocketjsonrpc::WsJsonRpcConnectionConfigPtr generate(const websocketjsonrpc::WsJsonRpcConnectionPtr &optional_failed_connection,
    int connect_retry_number);

  // We expect the config was generated by `ConnectionConfigGenerator::createConfig()` and was not modified later
  static eastl::string extractAuthorizationToken(const websocketjsonrpc::WsJsonRpcConnectionConfig &config);

  const eastl::string &getUserAgent() const { return userAgent; }

private:
  websocketjsonrpc::WsJsonRpcConnectionConfigPtr createConfig();

private:
  const bool verifyCert = true;
  const bool verifyHost = true;
  const LogLevel logLevel = LogLevel::DEFAULT;
  const int connectionTryTimeoutMs = -1;
  const ReconnectDelayConfig reconnectDelayConfig;
  const bool enableZstdDecompressionSupport = true;
  const eastl::string userAgent;

  eastl::string authorizationToken;

  UrlSelector urlSelector;

  bool isVeryFirstConnectionTry = true;
  int previousConnectRetryNumber = -1; // 0 means first try in a connect try sequence
  TickCount tickWhenToConnectAgain = 0;
};


} // namespace sepclient::details
