#undef LOTTIE_MODULE
#undef LOTTIE_IMAGE_MODULE_SUPPORT

#undef LOTTIE_THREAD
#undef LOTTIE_THREAD_SUPPORT

#undef LOTTIE_CACHE
#undef LOTTIE_CACHE_SUPPORT

#undef LOTTIE_LOGGING_SUPPORT
#define LOTTIE_NOSTDSTREAM_SUPPORT

#define LOTTIE_STLBASE_HAVE_TOSTRING

#define RLOTTIE_API
#include "eastl_config.h"
