#pragma once

#include <X11/keysym.h>

struct DrvMappedKeyNames
{
  int id, hid_id;
  const char *name;
};

static DrvMappedKeyNames kbdMappedNames[] = {
  {9, HumanInput::DKEY_ESCAPE, "Esc"},
  {0, 255, "Section-§"},
  {10, HumanInput::DKEY_1, "1"},
  {11, HumanInput::DKEY_2, "2"},
  {12, HumanInput::DKEY_3, "3"},
  {13, HumanInput::DKEY_4, "4"},
  {14, HumanInput::DKEY_5, "5"},
  {15, HumanInput::DKEY_6, "6"},
  {16, HumanInput::DKEY_7, "7"},
  {17, HumanInput::DKEY_8, "8"},
  {18, HumanInput::DKEY_9, "9"},
  {19, HumanInput::DKEY_0, "0"},
  {20, HumanInput::DKEY_MINUS, "-"},
  {21, HumanInput::DKEY_EQUALS, "="},
  {22, HumanInput::DKEY_BACK, "BackSpace"}, // XK_BackSpace
  {23, HumanInput::DKEY_TAB, "Tab"},
  {24, HumanInput::DKEY_Q, "Q"},
  {25, HumanInput::DKEY_W, "W"},
  {26, HumanInput::DKEY_E, "E"},
  {27, HumanInput::DKEY_R, "R"},
  {28, HumanInput::DKEY_T, "T"},
  {29, HumanInput::DKEY_Y, "Y"},
  {30, HumanInput::DKEY_U, "U"},
  {31, HumanInput::DKEY_I, "I"},
  {32, HumanInput::DKEY_O, "O"},
  {33, HumanInput::DKEY_P, "P"},
  {34, HumanInput::DKEY_LBRACKET, "["},
  {35, HumanInput::DKEY_RBRACKET, "]"},
  {36, HumanInput::DKEY_RETURN, "Enter"},
  {37, HumanInput::DKEY_LCONTROL, "L.Ctrl"},
  {38, HumanInput::DKEY_A, "A"},
  {39, HumanInput::DKEY_S, "S"},
  {40, HumanInput::DKEY_D, "D"},
  {41, HumanInput::DKEY_F, "F"},
  {42, HumanInput::DKEY_G, "G"},
  {43, HumanInput::DKEY_H, "H"},
  {44, HumanInput::DKEY_J, "J"},
  {45, HumanInput::DKEY_K, "K"},
  {46, HumanInput::DKEY_L, "L"},
  {47, HumanInput::DKEY_SEMICOLON, ";"},
  {48, HumanInput::DKEY_APOSTROPHE, "'"},
  {49, HumanInput::DKEY_GRAVE, "~"},
  {50, HumanInput::DKEY_LSHIFT, "L.Shift"},
  {51, HumanInput::DKEY_BACKSLASH, "\\"},
  {52, HumanInput::DKEY_Z, "Z"},
  {53, HumanInput::DKEY_X, "X"},
  {54, HumanInput::DKEY_C, "C"},
  {55, HumanInput::DKEY_V, "V"},
  {56, HumanInput::DKEY_B, "B"},
  {57, HumanInput::DKEY_N, "N"},
  {58, HumanInput::DKEY_M, "M"},
  {59, HumanInput::DKEY_COMMA, ","},
  {60, HumanInput::DKEY_PERIOD, "."},
  {61, HumanInput::DKEY_SLASH, "/"},
  {62, HumanInput::DKEY_RSHIFT, "R.Shift"},
  {63, HumanInput::DKEY_MULTIPLY, "*"},
  {64, HumanInput::DKEY_LALT, "L.Alt"},
  {65, HumanInput::DKEY_SPACE, "Space"},
  {66, HumanInput::DKEY_CAPITAL, "CapsLock"},
  {67, HumanInput::DKEY_F1, "F1"},
  {68, HumanInput::DKEY_F2, "F2"},
  {69, HumanInput::DKEY_F3, "F3"},
  {70, HumanInput::DKEY_F4, "F4"},
  {71, HumanInput::DKEY_F5, "F5"},
  {72, HumanInput::DKEY_F6, "F6"},
  {73, HumanInput::DKEY_F7, "F7"},
  {74, HumanInput::DKEY_F8, "F8"},
  {75, HumanInput::DKEY_F9, "F9"},
  {76, HumanInput::DKEY_F10, "F10"},
  {77, HumanInput::DKEY_NUMLOCK, "NumLock"},
  {78, HumanInput::DKEY_SCROLL, "ScrLock"},
  {79, HumanInput::DKEY_NUMPAD7, "Num7"},
  {80, HumanInput::DKEY_NUMPAD8, "Num8"},
  {81, HumanInput::DKEY_NUMPAD9, "Num9"},
  {82, HumanInput::DKEY_SUBTRACT, "Num-"},
  {83, HumanInput::DKEY_NUMPAD4, "Num4"},
  {84, HumanInput::DKEY_NUMPAD5, "Num5"},
  {85, HumanInput::DKEY_NUMPAD6, "Num6"},
  {86, HumanInput::DKEY_ADD, "Num+"},
  {87, HumanInput::DKEY_NUMPAD1, "Num1"},
  {88, HumanInput::DKEY_NUMPAD2, "Num2"},
  {89, HumanInput::DKEY_NUMPAD3, "Num3"},
  {90, HumanInput::DKEY_NUMPAD0, "Num0"},
  {91, HumanInput::DKEY_DECIMAL, "Num."},
  {95, HumanInput::DKEY_F11, "F11"},
  {96, HumanInput::DKEY_F12, "F12"},
  {104, HumanInput::DKEY_NUMPADENTER, "NumEnter"},
  {105, HumanInput::DKEY_RCONTROL, "R.Ctrl"},
  {106, HumanInput::DKEY_DIVIDE, "Num/"},
  {107, HumanInput::DKEY_SYSRQ, "SysRq"},
  {108, HumanInput::DKEY_RALT, "R.Alt"},
  {127, HumanInput::DKEY_PAUSE, "Pause"},
  {110, HumanInput::DKEY_HOME, "Home"},
  {111, HumanInput::DKEY_UP, "Up"},
  {112, HumanInput::DKEY_PRIOR, "PageUp"},
  {113, HumanInput::DKEY_LEFT, "Left"},
  {114, HumanInput::DKEY_RIGHT, "Right"},
  {115, HumanInput::DKEY_END, "End"},
  {116, HumanInput::DKEY_DOWN, "Down"},
  {117, HumanInput::DKEY_NEXT, "PageDown"},
  {118, HumanInput::DKEY_INSERT, "Insert"},
  {119, HumanInput::DKEY_DELETE, "Delete"},
  {133, HumanInput::DKEY_LWIN, "L.Cmd"},
  {134, HumanInput::DKEY_RWIN, "R.Cmd"},
  {135, HumanInput::DKEY_APPS, "AppMenu"},
};
