#!/bin/sh

root="$(git rev-parse --show-toplevel)"

files=$((git diff --cached --name-only --diff-filter=ACMR | grep -Ei "\.das$") || true)

if [ ! -z "${files}" ]; then
    result=0
    paths=""
    for it in $files; do
        paths+="--path ${it} "
    done
    daScript dasfmt.das -- ${paths} || result=1

    for it in $files; do
        git add "${it}"
    done
    exit $result
fi
