// Copyright 2016 The Draco Authors.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Auto-generated file. This file should be generated by CMake during the build.
// For manual builds (e.g., with Jam), this file defines the compilation features.
//
#ifndef DRACO_DRACO_FEATURES_H_
#define DRACO_DRACO_FEATURES_H_

// DRACO_MESH_COMPRESSION_SUPPORTED is always defined for standard Draco builds
// This feature allows assimp to know that the library is properly configured.
#define DRACO_MESH_COMPRESSION_SUPPORTED 1

// Major, minor, and patch version numbers
#define DRACO_VERSION_MAJOR 1
#define DRACO_VERSION_MINOR 5
#define DRACO_VERSION_PATCH 7

// Optional features that can be enabled/disabled at compile time
// These can be defined (1) or undefined based on the build configuration

// Encoder support - typically enabled
#define DRACO_ENABLE_ENCODER 1

// Decoder support - typically enabled
#define DRACO_ENABLE_DECODER 1

// Mesh compression/decompression
#define DRACO_MESH_COMPRESSION 1

// Point cloud compression/decompression
#define DRACO_POINT_CLOUD_COMPRESSION 1

// Animation compression support
#define DRACO_ANIMATION_COMPRESSION 1

// Attribute quantization during encoding
#define DRACO_ATTRIBUTE_QUANTIZATION 1

// Standard attribute types support
#define DRACO_STANDARD_EDGEBREAKER 1

// SSE, AVX, NEON optimizations - comment out if not supported on your platform
#define DRACO_USE_INTRINSICS 1

// SIMD optimizations
#define DRACO_FAST_PATH 1

// Compatibility flags
// These help ensure compatibility with various platforms

// Windows-specific settings
#ifdef _WIN32
  #define DRACO_WINDOWS 1
#endif

// macOS-specific settings
#ifdef __APPLE__
  #define DRACO_MAC 1
#endif

// Linux-specific settings
#ifdef __linux__
  #define DRACO_LINUX 1
#endif

// Android-specific settings
#ifdef __ANDROID__
  #define DRACO_ANDROID 1
#endif

#endif  // DRACO_DRACO_FEATURES_H_
