// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

#include "../av_cm.h"


enum
{
  ID_TEX_TILE = ID_SPEC_GRP + 1,

  ID_COLOR_MODE_GRP,
  ID_COLOR_MODE_R,
  ID_COLOR_MODE_G,
  ID_COLOR_MODE_B,
  ID_COLOR_MODE_RGB,
  ID_COLOR_MODE_A,
  ID_COLOR_MODE_RGBA,
  ID_COLOR_MODE_TOO_DARK,
  ID_COLOR_MODE_TOO_BRIGHT,
  ID_COLOR_MODE_SCALE,

  ID_INFO_GRP,
  ID_IES_INFO_GRP,

  ID_MIP_LEVEL,
  ID_STRETCH,
  ID_ALPHA_TEST,
  ID_MIP_STRIPE,
  ID_EXPORT_TEXTURE,
  ID_TC_Z,

  ID_TEX_SIZE_LABEL,
  ID_TEX_MIPS_LABEL,
  ID_TEX_MEMSZ_LABEL,

  ID_SHOW_TEXQ_GRP,
  ID_SHOW_TEXQ_STUB,
  ID_SHOW_TEXQ_THUMB,
  ID_SHOW_TEXQ_BASE,
  ID_SHOW_TEXQ_HIGH,
  ID_SHOW_TEXQ_UHQ,
};


enum
{
  ID_NEW_OBJ_NAME = 1,
  ID_NEW_OBJ_PATH,
};
