#ifndef APPLY_LOWRES_FX_HLSLI_INCLUDED
#define APPLY_LOWRES_FX_HLSLI_INCLUDED

#define APPLY_LOWRES_FX_TILE_SIZE (64)
#define CLASSIFY_LOWRES_FX_GROUP_SIZE (APPLY_LOWRES_FX_TILE_SIZE/4)

#endif // APPLY_LOWRES_FX_HLSLI_INCLUDED
