#ifndef RENDINST_HLSLI_INCLUDED
#define RENDINST_HLSLI_INCLUDED

#define INST_OFFSET_FLAG_USE_INDIRECTION (1u << 31u)
#define INST_OFFSET_MASK_VALUE           (0x7FFFFFFFu)

#endif // RENDINST_HLSLI_INCLUDED
