// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

#include <drv/hid/dag_hiKeybIds.h>
#include <EASTL/tuple.h>


namespace darg
{

static struct
{
  int id;
  const char *name;
} kbd_key_names[] = {
  {HumanInput::DKEY_ESCAPE, "Esc"},
  {HumanInput::DKEY_1, "1"},
  {HumanInput::DKEY_2, "2"},
  {HumanInput::DKEY_3, "3"},
  {HumanInput::DKEY_4, "4"},
  {HumanInput::DKEY_5, "5"},
  {HumanInput::DKEY_6, "6"},
  {HumanInput::DKEY_7, "7"},
  {HumanInput::DKEY_8, "8"},
  {HumanInput::DKEY_9, "9"},
  {HumanInput::DKEY_0, "0"},
  {HumanInput::DKEY_MINUS, "-"},
  {HumanInput::DKEY_EQUALS, "="},
  {HumanInput::DKEY_BACK, "Backspace"},
  {HumanInput::DKEY_TAB, "Tab"},
  {HumanInput::DKEY_Q, "Q"},
  {HumanInput::DKEY_W, "W"},
  {HumanInput::DKEY_E, "E"},
  {HumanInput::DKEY_R, "R"},
  {HumanInput::DKEY_T, "T"},
  {HumanInput::DKEY_Y, "Y"},
  {HumanInput::DKEY_U, "U"},
  {HumanInput::DKEY_I, "I"},
  {HumanInput::DKEY_O, "O"},
  {HumanInput::DKEY_P, "P"},
  {HumanInput::DKEY_LBRACKET, "["},
  {HumanInput::DKEY_RBRACKET, "]"},
  {HumanInput::DKEY_RETURN, "Enter"},
  {HumanInput::DKEY_LCONTROL, "L.Ctrl"},
  {HumanInput::DKEY_A, "A"},
  {HumanInput::DKEY_S, "S"},
  {HumanInput::DKEY_D, "D"},
  {HumanInput::DKEY_F, "F"},
  {HumanInput::DKEY_G, "G"},
  {HumanInput::DKEY_H, "H"},
  {HumanInput::DKEY_J, "J"},
  {HumanInput::DKEY_K, "K"},
  {HumanInput::DKEY_L, "L"},
  {HumanInput::DKEY_SEMICOLON, ";"},
  {HumanInput::DKEY_APOSTROPHE, "'"},
  {HumanInput::DKEY_GRAVE, "~"},
  {HumanInput::DKEY_LSHIFT, "L.Shift"},
  {HumanInput::DKEY_BACKSLASH, "\\"},
  {HumanInput::DKEY_Z, "Z"},
  {HumanInput::DKEY_X, "X"},
  {HumanInput::DKEY_C, "C"},
  {HumanInput::DKEY_V, "V"},
  {HumanInput::DKEY_B, "B"},
  {HumanInput::DKEY_N, "N"},
  {HumanInput::DKEY_M, "M"},
  {HumanInput::DKEY_COMMA, ","},
  {HumanInput::DKEY_PERIOD, "."},
  {HumanInput::DKEY_SLASH, "/"},
  {HumanInput::DKEY_RSHIFT, "R.Shift"},
  {HumanInput::DKEY_MULTIPLY, "*"},
  {HumanInput::DKEY_LALT, "L.Alt"},
  {HumanInput::DKEY_SPACE, "Space"},
  {HumanInput::DKEY_CAPITAL, "CapsLock"},
  {HumanInput::DKEY_F1, "F1"},
  {HumanInput::DKEY_F2, "F2"},
  {HumanInput::DKEY_F3, "F3"},
  {HumanInput::DKEY_F4, "F4"},
  {HumanInput::DKEY_F5, "F5"},
  {HumanInput::DKEY_F6, "F6"},
  {HumanInput::DKEY_F7, "F7"},
  {HumanInput::DKEY_F8, "F8"},
  {HumanInput::DKEY_F9, "F9"},
  {HumanInput::DKEY_F10, "F10"},
  {HumanInput::DKEY_NUMLOCK, "NumLock"},
  {HumanInput::DKEY_SCROLL, "ScrLock"},
  {HumanInput::DKEY_NUMPAD7, "Num7"},
  {HumanInput::DKEY_NUMPAD8, "Num8"},
  {HumanInput::DKEY_NUMPAD9, "Num9"},
  {HumanInput::DKEY_SUBTRACT, "Num-"},
  {HumanInput::DKEY_NUMPAD4, "Num4"},
  {HumanInput::DKEY_NUMPAD5, "Num5"},
  {HumanInput::DKEY_NUMPAD6, "Num6"},
  {HumanInput::DKEY_ADD, "Num+"},
  {HumanInput::DKEY_NUMPAD1, "Num1"},
  {HumanInput::DKEY_NUMPAD2, "Num2"},
  {HumanInput::DKEY_NUMPAD3, "Num3"},
  {HumanInput::DKEY_NUMPAD0, "Num0"},
  {HumanInput::DKEY_DECIMAL, "Num."},
  {HumanInput::DKEY_F11, "F11"},
  {HumanInput::DKEY_F12, "F12"},
  {HumanInput::DKEY_NUMPADENTER, "NumEnter"},
  {HumanInput::DKEY_RCONTROL, "R.Ctrl"},
  {HumanInput::DKEY_DIVIDE, "Num/"},
  {HumanInput::DKEY_SYSRQ, "SysRq"},
  {HumanInput::DKEY_RALT, "R.Alt"},
  {HumanInput::DKEY_PAUSE, "Pause"},
  {HumanInput::DKEY_HOME, "Home"},
  {HumanInput::DKEY_UP, "Up"},
  {HumanInput::DKEY_PRIOR, "PageUp"},
  {HumanInput::DKEY_LEFT, "Left"},
  {HumanInput::DKEY_RIGHT, "Right"},
  {HumanInput::DKEY_END, "End"},
  {HumanInput::DKEY_DOWN, "Down"},
  {HumanInput::DKEY_NEXT, "PageDown"},
  {HumanInput::DKEY_INSERT, "Insert"},
  {HumanInput::DKEY_DELETE, "Delete"},
  {HumanInput::DKEY_LWIN, "L.Cmd"},
  {HumanInput::DKEY_RWIN, "R.Cmd"},
  {HumanInput::DKEY_APPS, "AppMenu"},
};


} // namespace darg
