#pragma once

enum
{
  DEFAULT_GROUP_HEIGHT = 20,
  DEFAULT_TAB_HEIGHT = 28,
  DEFAULT_TAB_PAGE_OFFSET = 2,
  DEFAULT_CONTROL_HEIGHT = 20,
  DEFAULT_BUTTON_HEIGHT = 23,
  DEFAULT_SEPARATOR_HEIGHT = 2,
  DEFAULT_GROUP_FIRST_LINE = 22,
  DEFAULT_GROUP_WIDTH = 275,
  DEFAULT_LISTBOX_HEIGHT = 96,
  UP_DOWN_BUTTON_WIDTH = 15,
  DEFAULT_CONTROL_WIDTH = 60,
  DEFAULT_CONTROLS_INTERVAL = 8,
  GROUP_MINIMIZE_BUTTON_SIZE = 22,
  GROUP_MINIMIZE_BUTTON_X = 4,
  GROUP_MINIMIZE_BUTTON_Y = 2,
  TRACK_GRADIENT_BUTTON_WIDTH = 11,
  TRACK_GRADIENT_BUTTON_HEIGHT = 11,
  GRADIENT_HEIGHT = 20,
  TEXT_GRADIENT_HEIGHT = 30,
  DEFAULT_CURVE_HEIGHT = 150,         // 200
  DEFAULT_TOOLBAR_HEIGHT = 22,        // 28,
  DEFAULT_TOOLBAR_BUTTON_HEIGHT = 24, // 30,
  DEFAULT_TOOLBAR_CONTROL_WIDTH = 100,
  TOOLBAR_IMAGE_WH = 16, // 22,
  TRACK_LEADER_HEIGHT = 2,
  COMBO_HEIGHT_MUL = 10,
  DEFAULT_PALETTE_CELL_SIZE = 30,

  DEFAULT_TOOLWINDOW_IDENT = 2,

  DIALOG_BUTTONS_PANEL_HEIGHT = DEFAULT_BUTTON_HEIGHT + 2 * DEFAULT_CONTROLS_INTERVAL,
  DIALOG_BUTTONS_PANEL_WIDTH = 200,

  SCROLL_WHEEL_SMOOTHNESS = 4,
  CAPTION_SIZE = 128,
  FILTER_STRING_SIZE = 1024,
  STRING_SIZE = 512,
};
