#ifndef DAFX_MODFX_GPU_PLACEMENT_FLAGS_HLSL
#define DAFX_MODFX_GPU_PLACEMENT_FLAGS_HLSL

#define MODFX_GPU_PLACEMENT_HMAP (1 << 0)
#define MODFX_GPU_PLACEMENT_WATER (1 << 1)
#define MODFX_GPU_PLACEMENT_DEPTH_ABOVE (1 << 2)

#endif