// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

#include "driver.h"
#include <EASTL/bitset.h>


namespace drv3d_dx12
{
struct DeviceFeaturesConfig
{
  enum Bits
  {
    OPTIMIZE_BUFFER_UPLOADS,
    USE_THREADED_COMMAND_EXECUTION,
    USE_SYNCED_COMMAND_EXECUTION,
    PIPELINE_COMPILATION_ERROR_IS_FATAL,
    ASSERT_ON_PIPELINE_COMPILATION_ERROR,
    ALLOW_OS_MANAGED_SHADER_CACHE,
    ENABLE_DEFRAGMENTATION,
    DISABLE_PIPELINE_LIBRARY_CACHE,
#if _TARGET_SCARLETT
    REPORT_WAVE_64,
#endif
#if DX12_CONFIGUREABLE_BARRIER_MODE
    PROCESS_USER_BARRIERS,
    VALIDATE_USER_BARRIERS,
    GENERATE_ALL_BARRIERS,
#endif
#if DX12_DOES_SET_DEBUG_NAMES
    NAME_OBJECTS,
#endif
    ALLOW_STREAM_BUFFERS,
    ALLOW_STREAM_CONST_BUFFERS,
    ALLOW_STREAM_VERTEX_BUFFERS,
    ALLOW_STREAM_INDEX_BUFFERS,
    ALLOW_STREAM_INDIRECT_BUFFERS,
    ALLOW_STREAM_STAGING_BUFFERS,
#if DX12_ENABLE_CONST_BUFFER_DESCRIPTORS
    ROOT_SIGNATURES_USES_CBV_DESCRIPTOR_RANGES,
#endif
    VALIDATE_BINDLESS_TYPES,
    DISABLE_BUFFER_SUBALLOCATION,
    DISABLE_BINDLESS,
    IGNORE_PREDICATION,
    COUNT,
    INVLID = COUNT
  };
  typedef eastl::bitset<COUNT> Type;
};
} // namespace drv3d_dx12
