#ifndef DAFX_SPARK_FLAGS_DECL_HLSL
#define DAFX_SPARK_FLAGS_DECL_HLSL

#define DECL_ENABLED(p, a) ( (p) & ( 1 << (a) ) )

#define DAFX_SPARK_DECL_LOCAL_SPACE 0
#define DAFX_SPARK_DECL_LOCAL_SPACE_ENABLED(a) DECL_ENABLED(a, DAFX_SPARK_DECL_LOCAL_SPACE)

#define DAFX_SPARK_DECL_COLLISION_DISABLED_FLAG 1
#define DAFX_SPARK_DECL_COLLISION_DISABLED(a) DECL_ENABLED(a, DAFX_SPARK_DECL_COLLISION_DISABLED_FLAG)

#define DAFX_SPARK_DECL_COLLISION_RELAXED_FLAG 2
#define DAFX_SPARK_DECL_COLLISION_RELAXED(a) DECL_ENABLED(a, DAFX_SPARK_DECL_COLLISION_RELAXED_FLAG)

#define DAFX_SPARK_SMOOTH_FADE 3
#define DAFX_SPARK_SMOOTH_FADE_ENABLED(a) DECL_ENABLED(a, DAFX_SPARK_SMOOTH_FADE)

#endif