//
// Dagor Engine 6.5 - Game Libraries
// Copyright (C) 2023  Gaijin Games KFT.  All rights reserved
// (for conditions of use see prog/license.txt)
//
#pragma once

#define ECS_EXPAND_ARG(x)                      x
#define ECS_FOR_EACH_ARG_1(ARG, WHAT, X)       WHAT(ARG, X)
#define ECS_FOR_EACH_ARG_2(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_1(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_3(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_2(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_4(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_3(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_5(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_4(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_6(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_5(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_7(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_6(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_8(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_7(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_9(ARG, WHAT, X, ...)  WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_8(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_10(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_9(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_11(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_10(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_12(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_11(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_13(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_12(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_14(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_13(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_ARG_15(ARG, WHAT, X, ...) WHAT(ARG, X) ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_14(ARG, WHAT, __VA_ARGS__))
//... repeat as needed
#define ECS_FOR_EACH_ARG_NARG(...)             ECS_FOR_EACH_ARG_NARG_(__VA_ARGS__, ECS_FOR_EACH_ARG_RSEQ_N())
#define ECS_FOR_EACH_ARG_NARG_(...)            ECS_EXPAND_ARG(ECS_FOR_EACH_ARG_ARG_N(__VA_ARGS__))

#define ECS_FOR_EACH_ARG_ARG_N(_1, _2, _3, _4, _5, _6, _7, _8, _9, _10, _11, _12, _13, _14, _15, N, ...) N

#define ECS_FOR_EACH_ARG_RSEQ_N()             15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0
#define ECS_CONCATENATE(x, y)                 x##y
#define ECS_FOR_EACH_ARG_(N, ARG, WHAT, ...)  ECS_EXPAND_ARG(CONCATENATE(ECS_FOR_EACH_ARG_, N)(ARG, WHAT, __VA_ARGS__))
#define ECS_FOR_EACH_WITH_ARG(WHAT, ARG, ...) ECS_FOR_EACH_ARG_(ECS_FOR_EACH_ARG_NARG(__VA_ARGS__), ARG, WHAT, __VA_ARGS__)
