// This file is auto-generated during project deployment. Do not modify!
#define NRD_NORMAL_ENCODING 2
#define NRD_ROUGHNESS_ENCODING 1
#define NRD_SUPPORTS_VIEWPORT_OFFSET 0
#define NRD_SUPPORTS_CHECKERBOARD 1
#define NRD_SUPPORTS_HISTORY_CONFIDENCE 1
#define NRD_SUPPORTS_DISOCCLUSION_THRESHOLD_MIX 1
#define NRD_SUPPORTS_BASECOLOR_METALNESS 1
#define NRD_SUPPORTS_ANTIFIREFLY 1
#define REBLUR_PERFORMANCE_MODE 0
