// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

enum
{
  PID_SELECT_DYN_MODEL,

  PID_NODE_MASKS_GROUP,
  PID_NODE_MASKS_FILTER,
  PID_NODE_MASKS_TREE,
  PID_NODE_MASKS_ADD_MASK,
  PID_NODE_MASKS_ADD_NODE,
  PID_NODE_MASKS_REMOVE_NODE,
  PID_NODE_MASKS_SETTINGS_GROUP,
  PID_NODE_MASKS_NAME_FIELD,
  PID_NODE_MASKS_PATH_FIELD,
  PID_NODE_MASKS_SAVE,

  PID_ANIM_BLEND_NODES_GROUP,
  PID_ANIM_BLEND_NODES_SETTINGS_GROUP,
  PID_ANIM_BLEND_NODES_FILTER,
  PID_ANIM_BLEND_NODES_TREE,
  PID_ANIM_BLEND_NODES_A2D,
  PID_ANIM_BLEND_NODES_LEAF,
  PID_ANIM_BLEND_NODES_IRQ,
  PID_ANIM_BLEND_NODES_INCLUDE,
  PID_ANIM_BLEND_NODES_CREATE_NODE,
  PID_ANIM_BLEND_NODES_ADD_LEAF,
  PID_ANIM_BLEND_NODES_ADD_IRQ,
  PID_ANIM_BLEND_NODES_REMOVE_NODE,

  PID_ANIM_BLEND_CTRLS_GROUP,
  PID_ANIM_BLEND_CTRLS_SETTINGS_GROUP,
  PID_ANIM_BLEND_CTRLS_FILTER,
  PID_ANIM_BLEND_CTRLS_TREE,
  PID_ANIM_BLEND_CTRLS_ADD_NODE,
  PID_ANIM_BLEND_CTRLS_ADD_INCLUDE,
  PID_ANIM_BLEND_CTRLS_ADD_INNER_INCLUDE,
  PID_ANIM_BLEND_CTRLS_REMOVE_NODE,

  PID_ANIM_STATES_GROUP,
  PID_ANIM_STATES_FILTER,
  PID_ANIM_STATES_TREE,
  PID_ANIM_STATES_ADD_ENUM,
  PID_ANIM_STATES_ADD_ITEM,
  PID_ANIM_STATES_REMOVE_NODE,
  PID_ANIM_STATES_SETTINGS_GROUP,
  PID_ANIM_STATES_NAME_FIELD,

  PID_ANIM_STATES_ADD_STATE,
  PID_ANIM_STATES_ADD_CHAN,
  PID_ANIM_STATES_ADD_STATE_ALIAS,

  // Blend nodes settings pids
  PID_NODES_PARAMS_FIELD,
  PID_IRQ_INTERRUPTION_FIELD = PID_NODES_PARAMS_FIELD,
  PID_IRQ_NAME_FIELD,
  PID_NODES_PARAMS_FIELD_SIZE = PID_NODES_PARAMS_FIELD + 100,

  PID_NODES_ACTION_FIELD,
  PID_IRQ_TYPE_COMBO_SELECT = PID_NODES_ACTION_FIELD,
  PID_NODES_SETTINGS_NODE_TYPE_COMBO_SELECT,
  PID_NODES_SETTINGS_PLAY_ANIMATION,
  PID_NODES_SETTINGS_SAVE,
  PID_NODES_ACTION_FIELD_SIZE,

  // Ctrls settings pids
  PID_CTRLS_PARAMS_FIELD,
  PID_CTRLS_PARAMS_FIELD_SIZE = PID_CTRLS_PARAMS_FIELD + 100,

  PID_CTRLS_ACTION_FIELD,
  PID_CTRLS_TYPE_COMBO_SELECT = PID_CTRLS_ACTION_FIELD,
  PID_CTRLS_SEPARATOR,

  PID_CTRLS_TARGET_NODE_ADD,
  PID_CTRLS_TARGET_NODE_REMOVE,

  PID_CTRLS_PARAM_SWITCH_TYPE_COMBO_SELECT,
  PID_CTRLS_PARAM_SWITCH_ENUM_GEN_COMBO_SELECT,
  PID_CTRLS_PARAM_SWITCH_NAME_TEMPLATE,

  PID_CTRLS_PARAM_SWITCH_NODE_ENUM_ITEM,
  PID_CTRLS_PARAM_SWITCH_NODE_NAME,
  PID_CTRLS_PARAM_SWITCH_NODE_RANGE_FROM,
  PID_CTRLS_PARAM_SWITCH_NODE_RANGE_TO,

  PID_CTRLS_NODES_LIST,
  PID_CTRLS_NODES_LIST_ADD,
  PID_CTRLS_NODES_LIST_REMOVE,

  PID_CTRLS_RANDOM_SWITCH_NODE_NAME,
  PID_CTRLS_RANDOM_SWITCH_NODE_WEIGHT,
  PID_CTRLS_RANDOM_SWITCH_NODE_MAX_REPEAT,

  PID_CTRLS_HUB_NODE_NAME,
  PID_CTRLS_HUB_NODE_OPTIONAL,
  PID_CTRLS_HUB_NODE_ENABLED,
  PID_CTRLS_HUB_NODE_WEIGHT,

  PID_CTRLS_LINEAR_POLY_NODE_NAME,
  PID_CTRLS_LINEAR_POLY_NODE_VAL,

  PID_CTRLS_SETTINGS_SAVE,
  PID_CTRLS_ACTION_FIELD_SIZE,

  // States settings pids
  PID_STATES_PARAMS_FIELD,
  PID_STATES_PARAMS_FIELD_SIZE = PID_STATES_PARAMS_FIELD + 100,

  PID_STATES_ACTION_FIELD,
  PID_STATES_STATE_DESC_TYPE_COMBO_SELECT = PID_STATES_ACTION_FIELD,
  PID_STATES_SETTINGS_SAVE,
  PID_STATES_ACTION_FIELD_SIZE,
};
