// Copyright (C) Gaijin Games KFT.  All rights reserved.
#pragma once

enum
{
  PID_SELECT_DYN_MODEL_STATIC,
  PID_SELECT_DYN_MODEL,
  PID_VALIDATE_DEPENDENT_NODES,

  PID_NODE_MASKS_GROUP,
  PID_NODE_MASKS_FILTER,
  PID_NODE_MASKS_TREE,
  PID_NODE_MASKS_ADD_MASK,
  PID_NODE_MASKS_ADD_NODE,
  PID_NODE_MASKS_REMOVE_NODE,
  PID_NODE_MASKS_SETTINGS_GROUP,
  PID_NODE_MASKS_NAME_FIELD,
  PID_NODE_MASKS_PATH_FIELD,
  PID_NODE_MASKS_SAVE,

  PID_ANIM_BLEND_NODES_GROUP,
  PID_ANIM_BLEND_NODES_SETTINGS_GROUP,
  PID_ANIM_BLEND_NODES_FILTER,
  PID_ANIM_BLEND_NODES_TREE,
  PID_ANIM_BLEND_NODES_A2D,
  PID_ANIM_BLEND_NODES_LEAF,
  PID_ANIM_BLEND_NODES_IRQ,
  PID_ANIM_BLEND_NODES_INCLUDE,
  PID_ANIM_BLEND_NODES_CREATE_NODE,
  PID_ANIM_BLEND_NODES_ADD_LEAF,
  PID_ANIM_BLEND_NODES_ADD_IRQ,
  PID_ANIM_BLEND_NODES_REMOVE_NODE,

  PID_ANIM_BLEND_CTRLS_GROUP,
  PID_ANIM_BLEND_CTRLS_SETTINGS_GROUP,
  PID_ANIM_BLEND_CTRLS_FILTER,
  PID_ANIM_BLEND_CTRLS_TREE,
  PID_ANIM_BLEND_CTRLS_ADD_NODE,
  PID_ANIM_BLEND_CTRLS_ADD_INCLUDE,
  PID_ANIM_BLEND_CTRLS_ADD_INNER_INCLUDE,
  PID_ANIM_BLEND_CTRLS_REMOVE_NODE,

  PID_ANIM_STATES_GROUP,
  PID_ANIM_STATES_FILTER,
  PID_ANIM_STATES_TREE,
  PID_ANIM_STATES_ADD_ENUM,
  PID_ANIM_STATES_ADD_ITEM,
  PID_ANIM_STATES_REMOVE_NODE,
  PID_ANIM_STATES_SETTINGS_GROUP,
  PID_ANIM_STATES_NAME_FIELD,

  PID_ANIM_STATES_ADD_STATE,
  PID_ANIM_STATES_ADD_CHAN,
  PID_ANIM_STATES_ADD_STATE_ALIAS,

  // Blend nodes settings pids
  PID_NODES_PARAMS_FIELD,
  PID_IRQ_INTERRUPTION_FIELD = PID_NODES_PARAMS_FIELD,
  PID_IRQ_NAME_FIELD,
  PID_NODES_INCLUDE_NAME_FIELD = PID_NODES_PARAMS_FIELD,
  PID_NODES_INCLUDE_PATH_FIELD,
  PID_NODES_PARAMS_FIELD_SIZE = PID_NODES_PARAMS_FIELD + 100,

  PID_NODES_ACTION_FIELD,
  PID_IRQ_TYPE_COMBO_SELECT = PID_NODES_ACTION_FIELD,
  PID_NODES_SETTINGS_NODE_TYPE_COMBO_SELECT,
  PID_NODES_SETTINGS_PLAY_ANIMATION,
  PID_NODES_SETTINGS_SAVE,
  PID_NODES_ACTION_FIELD_SIZE,

  // Ctrls settings pids
  PID_CTRLS_PARAMS_FIELD,
  PID_CTRLS_INCLUDE_NAME_FIELD = PID_CTRLS_PARAMS_FIELD,
  PID_CTRLS_INCLUDE_PATH_FIELD,
  PID_CTRLS_PARAMS_FIELD_SIZE = PID_CTRLS_PARAMS_FIELD + 100,

  PID_CTRLS_ACTION_FIELD,
  PID_CTRLS_TYPE_COMBO_SELECT = PID_CTRLS_ACTION_FIELD,
  PID_CTRLS_SEPARATOR,

  PID_CTRLS_TARGET_NODE_ADD,
  PID_CTRLS_TARGET_NODE_REMOVE,

  PID_CTRLS_PARAM_SWITCH_TYPE_COMBO_SELECT,
  PID_CTRLS_PARAM_SWITCH_ENUM_GEN_COMBO_SELECT,
  PID_CTRLS_PARAM_SWITCH_NAME_TEMPLATE,

  PID_CTRLS_PARAM_SWITCH_NODE_ENUM_ITEM,
  PID_CTRLS_PARAM_SWITCH_NODE_NAME,
  PID_CTRLS_PARAM_SWITCH_NODE_OPTIONAL,
  PID_CTRLS_PARAM_SWITCH_NODE_RANGE_FROM,
  PID_CTRLS_PARAM_SWITCH_NODE_RANGE_TO,

  PID_CTRLS_NODES_LIST,
  PID_CTRLS_NODES_LIST_ADD,
  PID_CTRLS_NODES_LIST_REMOVE,

  PID_CTRLS_RANDOM_SWITCH_NODE_NAME,
  PID_CTRLS_RANDOM_SWITCH_NODE_WEIGHT,
  PID_CTRLS_RANDOM_SWITCH_NODE_MAX_REPEAT,

  PID_CTRLS_HUB_NODE_NAME,
  PID_CTRLS_HUB_NODE_OPTIONAL,
  PID_CTRLS_HUB_NODE_ENABLED,
  PID_CTRLS_HUB_NODE_WEIGHT,

  PID_CTRLS_LINEAR_POLY_NODE_NAME,
  PID_CTRLS_LINEAR_POLY_NODE_VAL,

  PID_CTRLS_FOOT_LOCKER_IK_HIP,
  PID_CTRLS_FOOT_LOCKER_IK_KNEE,
  PID_CTRLS_FOOT_LOCKER_IK_ANKLE,
  PID_CTRLS_FOOT_LOCKER_IK_TOE,

  PID_CTRLS_NODES_FROM_ATTACHEMENT_SRC_NODE,
  PID_CTRLS_NODES_FROM_ATTACHEMENT_DEST_NODE,
  PID_CTRLS_NODES_FROM_ATTACHEMENT_RECURSIVE,
  PID_CTRLS_NODES_FROM_ATTACHEMENT_INCLUDING_ROOT,

  PID_CTRLS_EFF_FROM_ATTACHMENT_NODE,
  PID_CTRLS_EFF_FROM_ATTACHMENT_DEST_NODE,
  PID_CTRLS_EFF_FROM_ATTACHMENT_EFFECTOR,
  PID_CTRLS_EFF_FROM_ATTACHMENT_WRITE_MATRIX,
  PID_CTRLS_EFF_FROM_ATTACHMENT_WT_MODULATE,
  PID_CTRLS_EFF_FROM_ATTACHMENT_WT_MODULATE_INVERSE,

  PID_CTRLS_ATTACH_NODE_NODE,
  PID_CTRLS_ATTACH_NODE_VAR,
  PID_CTRLS_ATTACH_NODE_WT_MODULATE,
  PID_CTRLS_ATTACH_NODE_WT_MODULATE_INVERSE,

  PID_CTRLS_DEF_CLAMP_CTRL_PARAM,
  PID_CTRLS_DEF_CLAMP_CTRL_DEFAULT,
  PID_CTRLS_DEF_CLAMP_CTRL_CLAMP,

  PID_CTRLS_AIM_LIMIT_NAME,
  PID_CTRLS_AIM_LIMIT_VALUE,

  PID_CTRLS_LEGS_IK_BLOCK_TYPE,
  PID_CTRLS_LEGS_IK_LEG,
  PID_CTRLS_LEGS_IK_KNEE,
  PID_CTRLS_LEGS_IK_FOOT,
  PID_CTRLS_LEGS_IK_FOOT_STEP,
  PID_CTRLS_LEGS_IK_FOOT_STEP_RANGE,
  PID_CTRLS_LEGS_IK_FOOT_ROT_RANGE,
  PID_CTRLS_LEGS_IK_MAX_FOOT_UP,
  PID_CTRLS_LEGS_IK_FOOT_FWD,
  PID_CTRLS_LEGS_IK_FOOT_SIDE,
  PID_CTRLS_LEGS_IK_MAX_DY_RATE,
  PID_CTRLS_LEGS_IK_MAX_DA_RATE,
  PID_CTRLS_LEGS_IK_USE_ANIMCHAR_UP_DIR,
  PID_CTRLS_LEGS_IK_REVERSE_FLEX_DIRECTION,

  PID_CTRLS_MULTI_CHAIN_FABRIK_BLOCK_TYPE_COMBO_SELECT,
  PID_CTRLS_MULTI_CHAIN_FABRIK_EFFECTOR,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END,
  PID_CTRLS_MULTI_CHAIN_FABRIK_WT_MODULATE,
  PID_CTRLS_MULTI_CHAIN_FABRIK_WT_MODULATE_INVERSE,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START_TRI_GROUP,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START_TRI_NODE0,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START_TRI_NODE1,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START_TRI_ADD,
  PID_CTRLS_MULTI_CHAIN_FABRIK_START_TRI_SUB,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END_TRI_GROUP,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END_TRI_NODE0,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END_TRI_NODE1,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END_TRI_ADD,
  PID_CTRLS_MULTI_CHAIN_FABRIK_END_TRI_SUB,

  PID_CTRLS_ANIMATE_NODE_PARAM,
  PID_CTRLS_ANIMATE_NODE_BNL,
  PID_CTRLS_ANIMATE_NODE_S_KEY,
  PID_CTRLS_ANIMATE_NODE_E_KEY,
  PID_CTRLS_ANIMATE_NODE_P_MUL,
  PID_CTRLS_ANIMATE_NODE_P_ADD,
  PID_CTRLS_ANIMATE_NODE_ALWAYS_UPDATE,
  PID_CTRLS_ANIMATE_NODE_MANDATORY_ANIM,
  PID_CTRLS_ANIMATE_NODE_MANDATORY_NODES,
  PID_CTRLS_ANIMATE_NODE_ARRAY_NODES_ONLY,

  PID_CTRLS_ANIMATE_NODE_NODES_FIELD,
  PID_CTRLS_ANIMATE_NODE_NODES_FIELD_SIZE = PID_CTRLS_ANIMATE_NODE_NODES_FIELD + 50,

  PID_CTRLS_ANIMATE_NODE_RE_NODES_FIELD,
  PID_CTRLS_ANIMATE_NODE_RE_NODES_FIELD_SIZE = PID_CTRLS_ANIMATE_NODE_RE_NODES_FIELD + 50,

  PID_CTRLS_ANIMATE_NODE_ADD_NODE,
  PID_CTRLS_ANIMATE_NODE_REMOVE_NODE,
  PID_CTRLS_ANIMATE_NODE_ADD_NODE_RE,
  PID_CTRLS_ANIMATE_NODE_REMOVE_NODE_RE,

  PID_CTRLS_COND_HIDE_NODE,
  PID_CTRLS_COND_HIDE_ALWAYS,
  PID_CTRLS_COND_HIDE_HIDE_ONLY,
  PID_CTRLS_COND_HIDE_CONDITION,

  PID_CTRLS_PARAMS_CTRL_IF_MATH_FIELD,
  PID_CTRLS_PARAMS_CTRL_IF_MATH_FIELD_SIZE = PID_CTRLS_PARAMS_CTRL_IF_MATH_FIELD + 50,
  PID_CTRLS_PARAMS_CTRL_IF_MATH_ADD,
  PID_CTRLS_PARAMS_CTRL_IF_MATH_REMOVE,

  PID_CTRLS_PARAMS_CTRL_BLOCK_TYPE_COMBO_SELECT,
  PID_CTRLS_PARAMS_CTRL_CHANGE_PARAM,
  PID_CTRLS_PARAMS_CTRL_CHANGE_RATE,
  PID_CTRLS_PARAMS_CTRL_CHANGE_MOD,
  PID_CTRLS_PARAMS_CTRL_CHANGE_RATE_SRC,
  PID_CTRLS_PARAMS_CTRL_CHANGE_RATE_PARAM,
  PID_CTRLS_PARAMS_CTRL_CHANGE_SCALE_SRC,
  PID_CTRLS_PARAMS_CTRL_CHANGE_SCALE_PARAM,
  PID_CTRLS_PARAMS_CTRL_REMAP_PARAM,
  PID_CTRLS_PARAMS_CTRL_REMAP_DEST_PARAM,
  PID_CTRLS_PARAMS_CTRL_REMAP_ADD_MAPPING,
  PID_CTRLS_PARAMS_CTRL_REMAP_REMOVE_MAPPING,
  PID_CTRLS_PARAMS_CTRL_REMAP_MAPPING_FIELD,
  PID_CTRLS_PARAMS_CTRL_REMAP_MAPPING_FIELD_SIZE = PID_CTRLS_PARAMS_CTRL_REMAP_MAPPING_FIELD + 50,

  PID_CTRLS_SETTINGS_SAVE,
  PID_CTRLS_ACTION_FIELD_SIZE,

  // Dependent ctrl field pids
  // This pids used for multiple controllers with same fields by name
  PID_CTRLS_DEPENDENT_WT_MODULATE,
  PID_CTRLS_DEPENDENT_WT_MODULATE_INVERSE,
  PID_CTRLS_DEPENDENT_BNL,
  PID_CTRLS_DEPENDENT_S_KEY,
  PID_CTRLS_DEPENDENT_E_KEY,
  PID_CTRLS_DEPENDENT_MANDATORY_ANIM,

  // States settings pids
  PID_STATES_PARAMS_FIELD,
  PID_STATES_PARAMS_FIELD_SIZE = PID_STATES_PARAMS_FIELD + 100,

  PID_STATES_ACTION_FIELD,
  PID_STATES_STATE_DESC_TYPE_COMBO_SELECT = PID_STATES_ACTION_FIELD,

  PID_STATES_NODES_LIST,
  PID_STATES_NODES_LIST_ADD,
  PID_STATES_NODES_LIST_REMOVE,

  PID_STATES_STATE_NODE_CHANNEL,
  PID_STATES_STATE_NODE_NAME,
  PID_STATES_STATE_NODE_FORCE_DUR,
  PID_STATES_STATE_NODE_FORCE_SPD,
  PID_STATES_STATE_NODE_MORPH_TIME,
  PID_STATES_STATE_NODE_MIN_TIME_SCALE,
  PID_STATES_STATE_NODE_MAX_TIME_SCALE,

  PID_STATES_ENUM_PARAM_SWITCH_NAME,
  PID_STATES_ENUM_PARAM_SWITCH_VALUE,
  PID_STATES_ENUM_ENUM_ITEM_VALUE,

  PID_STATES_FIFO3_INIT_NAME,
  PID_STATES_FIFO3_INIT_VALUE,

  PID_STATES_POST_BLEND_CTRL_ORDER_NAME,

  PID_STATES_SETTINGS_SAVE,
  PID_STATES_ACTION_FIELD_SIZE,
};
