#pragma once

enum
{
  ASSET_USER_FLG_UP_TO_DATE_PC = 1 << 0,
  ASSET_USER_FLG_UP_TO_DATE_XBOX = 1 << 1,
  ASSET_USER_FLG_UP_TO_DATE_PS3 = 1 << 2,
  ASSET_USER_FLG_UP_TO_DATE_iOS = 1 << 3,
  ASSET_USER_FLG_UP_TO_DATE_AND = 1 << 4,
  ASSET_USER_FLG_UP_TO_DATE_PS4 = 1 << 5,
  ASSET_USER_FLG_NEEDS_RELOAD = 1 << 6,
};
