#define OCCLUSION_INVWBUFFER 1
#define OCCLUSION_WBUFFER    2
#define OCCLUSION_Z_BUFFER   3
#define OCCLUSION_BUFFER \
  OCCLUSION_INVWBUFFER // OCCLUSION_WBUFFER////OCCLUSION_WBUFFER////OCCLUSION_WBUFFER//OCCLUSION_INVWBUFFER//OCCLUSION_Z_BUFFER//
