#include <dagi_rad_grid.hlsli>
#include <dagi_irrad_grid.hlsli>

#define RAD_GRID_PROBABILITY_MUL 65535//no need to have better precision if we only use 16 bit hash
#define RAD_GRID_TEMPORAL_AGE_BITS 5
#define RAD_GRID_TEMPORAL_MAX_AGE_MASK ((1<<RAD_GRID_TEMPORAL_AGE_BITS) - 1)
#define RAD_GRID_TEMPORAL_MAX_LERP_AGE 27u
#define RAD_GRID_TEMPORAL_MAX_AGE (RAD_GRID_TEMPORAL_MAX_LERP_AGE < RAD_GRID_TEMPORAL_MAX_AGE_MASK ? RAD_GRID_TEMPORAL_MAX_LERP_AGE : RAD_GRID_TEMPORAL_MAX_AGE_MASK)
#define RAD_GRID_TEMPORAL_AGE_SHIFT (32 - RAD_GRID_TEMPORAL_AGE_BITS)
#define RAD_GRID_TEMPORAL_PROBE_BITS (RAD_GRID_TEMPORAL_AGE_SHIFT-1)
#define RAD_GRID_TEMPORAL_PROBE_MASK ((1<<RAD_GRID_TEMPORAL_PROBE_BITS)-1)
#define RAD_GRID_TEMPORAL_SCENE_PROXIMITY_BIT (1<<RAD_GRID_TEMPORAL_PROBE_BITS)

#define RAD_GRID_TEMPORAL_DATA_OFFSET (DAGI_MAX_RAD_GRID_CLIPS*8 + DAGI_MAX_IRRAD_GRID_CLIPS*8 + 4)