#include <dagi_rad_grid.hlsli>
#include <dagi_irrad_grid.hlsli>

#define RAD_GRID_PROBABILITY_MUL 65535//no need to have better precision if we only use 16 bit hash
#define RAD_GRID_TEMPORAL_AGE_BITS 6
#define RAD_GRID_TEMPORAL_MAX_ENCODED_AGE ((1<<RAD_GRID_TEMPORAL_AGE_BITS) - 1)
#define RAD_GRID_TEMPORAL_MAX_AVAILABLE_QUICK_UPDATE_FRAMES 36
#define RAD_GRID_TEMPORAL_MIN_QUICK_UPDATE_REV_AGE (RAD_GRID_TEMPORAL_MAX_ENCODED_AGE - RAD_GRID_TEMPORAL_MAX_AVAILABLE_QUICK_UPDATE_FRAMES)
#define RAD_GRID_TEMPORAL_MAX_REV_AGE (RAD_GRID_TEMPORAL_MIN_QUICK_UPDATE_REV_AGE - 1)
#define RAD_GRID_TEMPORAL_AGE_SHIFT (32 - RAD_GRID_TEMPORAL_AGE_BITS)
#define RAD_GRID_TEMPORAL_PROBE_BITS (RAD_GRID_TEMPORAL_AGE_SHIFT-1)
#define RAD_GRID_TEMPORAL_PROBE_MASK ((1<<RAD_GRID_TEMPORAL_PROBE_BITS)-1)
#define RAD_GRID_TEMPORAL_SCENE_PROXIMITY_BIT (1<<RAD_GRID_TEMPORAL_PROBE_BITS)

#define RAD_GRID_TEMPORAL_DATA_OFFSET ((DAGI_MAX_RAD_GRID_CLIPS + DAGI_MAX_IRRAD_GRID_CLIPS + 1) * 4)