#define NBS_SHADER 1

//For Gbuffer:
#define NEED_MOTION_VECTOR_UNPACKING 1
#define GBUFFER_IN_EDITOR 0
#define RW_PREFIX

#define IS_ENVI_COVER 1
#define USE_SPARKLES_3D_NOISE 1

#define USE_CAMERA_IN_CAMERA 1

#ifndef ENVI_COVER_NBS_WITH_PACKED_NORMS
  #define ENVI_COVER_NBS_WITH_PACKED_NORMS 0
#endif

#ifndef GBUFFER_NORMALS_PACKED
  #define GBUFFER_NORMALS_PACKED 0
#endif