#define RADIANCE_CACHE_RADIANCE_RES 8
#define RADIANCE_CACHE_IRRADIANCE_RES_WITH_BORDER RADIANCE_CACHE_RADIANCE_RES
#define RADIANCE_CACHE_IRRADIANCE_RES (RADIANCE_CACHE_IRRADIANCE_RES_WITH_BORDER - 2)

#define RADIANCE_CACHE_TEMPORAL_AGE_BITS 8
#define RADIANCE_CACHE_TEMPORAL_AGE_SHIFT (32-RADIANCE_CACHE_TEMPORAL_AGE_BITS)
#define RADIANCE_CACHE_TEMPORAL_AGE_MAX ((1<<RADIANCE_CACHE_TEMPORAL_AGE_BITS) - 2) // maxval is invalid age
#define RADIANCE_CACHE_FRAME_UPDATED_MASK ((1<<RADIANCE_CACHE_TEMPORAL_AGE_SHIFT)-1)
#define RADIANCE_CACHE_INVALID_AGE (~0u)

