#ifndef PUDDLE_QUERY_HLSL_INCLUDED
#define PUDDLE_QUERY_HLSL_INCLUDED 1

#define PUDDLE_QUERY_WARP_SIZE 64

#define MAX_PUDDLE_QUERIES_PER_FRAME 100
#define MAX_PUDDLE_QUERIES_PER_DISPATCH MAX_PUDDLE_QUERIES_PER_FRAME

#endif