#ifndef _GAIJIN_RACE_UTILS_GAMEPAD_BUTTONS_H
#define _GAIJIN_RACE_UTILS_GAMEPAD_BUTTONS_H
#pragma once

enum GamepadButtonId
{
  JOY_BTN_D_UP = 0,
  JOY_BTN_D_DOWN = 1,
  JOY_BTN_D_LEFT = 2,
  JOY_BTN_D_RIGHT = 3,

  JOY_BTN_START = 4,
  JOY_BTN_BACK = 5,

  JOY_BTN_L_THUMB = 6,
  JOY_BTN_R_THUMB = 7,
  JOY_BTN_L_SHOULDER = 8,
  JOY_BTN_R_SHOULDER = 9,
  JOY_BTN_0X0400 = 10,
  JOY_BTN_0X0800 = 11,

  JOY_BTN_A = 12,
  JOY_BTN_B = 13,
  JOY_BTN_X = 14,
  JOY_BTN_Y = 15,

  JOY_BTN_L_TRIGGER = 16,
  JOY_BTN_R_TRIGGER = 17,
  JOY_BTN_L_THUMB_RIGHT = 18,
  JOY_BTN_L_THUMB_LEFT = 19,
  JOY_BTN_L_THUMB_UP = 20,
  JOY_BTN_L_THUMB_DOWN = 21,
  JOY_BTN_R_THUMB_RIGHT = 22,
  JOY_BTN_R_THUMB_LEFT = 23,
  JOY_BTN_R_THUMB_UP = 24,
  JOY_BTN_R_THUMB_DOWN = 25,

  JOY_BTN_NUM
};

// aliases
#define JOY_BTN_TRIANGLE JOY_BTN_Y
#define JOY_BTN_CIRCLE   JOY_BTN_B
#define JOY_BTN_CROSS    JOY_BTN_A
#define JOY_BTN_SQUARE   JOY_BTN_X

enum GamepadAxisId
{
  JOY_AXIS_L_HOR = 0,
  JOY_AXIS_L_VERT = 1,
  JOY_AXIS_R_HOR = 2,
  JOY_AXIS_R_VERT = 3,
  JOY_AXIS_L_TRIGGER = 4,
  JOY_AXIS_R_TRIGGER = 5,
};

#endif
