#ifndef DAGDP_GRID3D_PLACER_HLSLI_INCLUDED
#define DAGDP_GRID3D_PLACER_HLSLI_INCLUDED

#define GRID3D_TILE_SIZE 8
#define GRID3D_GROUP_SIZE (GRID3D_TILE_SIZE * GRID3D_TILE_SIZE * GRID3D_TILE_SIZE)

struct Grid3dTile
{
  int3 pos;
  uint volumeRange;
};

#endif // DAGDP_GRID3D_PLACER_HLSLI_INCLUDED
