//
// Dagor Engine 6.5
// Copyright (C) 2023  Gaijin Games KFT.  All rights reserved
// (for conditions of use see prog/license.txt)
//
#pragma once

#include <generic/dag_carray.h>

namespace HumanInput
{
enum
{
  TVOS_REMOTE_BUTTONS_BEGIN = 91,

  TVOS_REMOTE_DPAD_TAP_TOP_LEFT = TVOS_REMOTE_BUTTONS_BEGIN,
  TVOS_REMOTE_DPAD_TAP_TOP_CENTER = 92,
  TVOS_REMOTE_DPAD_TAP_TOP_RIGHT = 93,
  TVOS_REMOTE_DPAD_TAP_CENTER_LEFT = 94,
  TVOS_REMOTE_DPAD_TAP_CENTER = 95,
  TVOS_REMOTE_DPAD_TAP_CENTER_RIGHT = 96,
  TVOS_REMOTE_DPAD_TAP_BOTTOM_LEFT = 97,
  TVOS_REMOTE_DPAD_TAP_BUTTOM_CENTER = 98,
  TVOS_REMOTE_DPAD_TAP_BOTTOM_RIGHT = 99,

  TVOS_REMOTE_MOVEMENT_FORWARD = 100,
  TVOS_REMOTE_MOVEMENT_BACK = 101,
  TVOS_REMOTE_ROTATION_LEFT = 102,
  TVOS_REMOTE_ROTATION_RIGHT = 103,

  TVOS_REMOTE_DPAD_CLICK_TOP_LEFT = 104,
  TVOS_REMOTE_DPAD_CLICK_TOP_CENTER = 105,
  TVOS_REMOTE_DPAD_CLICK_TOP_RIGHT = 106,
  TVOS_REMOTE_DPAD_CLICK_CENTER_LEFT = 107,
  TVOS_REMOTE_DPAD_CLICK_CENTER = 108,
  TVOS_REMOTE_DPAD_CLICK_CENTER_RIGHT = 109,
  TVOS_REMOTE_DPAD_CLICK_BOTTOM_LEFT = 110,
  TVOS_REMOTE_DPAD_CLICK_BUTTOM_CENTER = 111,
  TVOS_REMOTE_DPAD_CLICK_BOTTOM_RIGHT = 112,

  TVOS_REMOTE_DPAD_SWIPE_UP = 113,
  TVOS_REMOTE_DPAD_SWIPE_DOWN = 114,
  TVOS_REMOTE_DPAD_SWIPE_UP_DOWN = 115,
  TVOS_REMOTE_DPAD_SWIPE_DOWN_UP = 116,
  TVOS_REMOTE_DPAD_SWIPE_LEFT = 117,
  TVOS_REMOTE_DPAD_SWIPE_RIGHT = 118,
  TVOS_REMOTE_DPAD_SWIPE_LEFT_RIGHT = 119,
  TVOS_REMOTE_DPAD_SWIPE_RIGHT_LEFT = 120,
  TVOS_REMOTE_BUTTON_X = 121,
  TVOS_REMOTE_BUTTON_MENU = 122,

  TVOS_REMOTE_MOVE_UP = 123,
  TVOS_REMOTE_MOVE_DOWN = 124,
  TVOS_REMOTE_MOVE_LEFT = 125,
  TVOS_REMOTE_MOVE_RIGHT = 126,

  TVOS_REMOTE_BUTTONS_END,
  TVOS_REMOTE_BUTTONS_COUNT = TVOS_REMOTE_BUTTONS_END - TVOS_REMOTE_BUTTONS_BEGIN,
};

static carray<const char *, TVOS_REMOTE_BUTTONS_COUNT> tvosRemoteButtonName = {
  "MOVEMENT_FORWARD",
  "MOVEMENT_BACK",
  "ROTATION_LEFT",
  "ROTATION_RIGHT",

  "DPAD_CLICK_TOP_LEFT",
  "DPAD_CLICK_TOP_CENTER",
  "DPAD_CLICK_TOP_RIGHT",
  "DPAD_CLICK_BOTTOM_LEFT",
  "DPAD_CLICK_BUTTOM_CENTER",
  "DPAD_CLICK_BOTTOM_RIGHT",
  "DPAD_CLICK_CENTER_LEFT",
  "DPAD_CLICK_CENTER",
  "DPAD_CLICK_CENTER_RIGHT",

  "DPAD_SWIPE_UP",
  "DPAD_SWIPE_DOWN",
  "DPAD_SWIPE_UP_DOWN",
  "DPAD_SWIPE_DOWN_UP",
  "DPAD_SWIPE_LEFT",
  "DPAD_SWIPE_RIGHT",
  "DPAD_SWIPE_LEFT_RIGHT",
  "DPAD_SWIPE_RIGHT_LEFT",
  "BUTTON_X",
  "BUTTON_MENU",

  "MOVE_UP",
  "MOVE_DOWN",
  "MOVE_LEFT",
  "MOVE_RIGHT",
};
} // namespace HumanInput
