#ifndef _GAIJIN_DASCRIPT_MODULES_RAPIDJSON_RAPIDJSONCONFIG_H_
#define _GAIJIN_DASCRIPT_MODULES_RAPIDJSON_RAPIDJSONCONFIG_H_
#pragma once

#ifndef RAPIDJSON_ASSERT
#include <debug/dag_assert.h>
#define RAPIDJSON_ASSERT G_ASSERT
#endif

#ifdef __AVX__
#define RAPIDJSON_SSE42 1
#elif (_TARGET_SIMD_SSE >= 2)
#define RAPIDJSON_SSE2 1
#endif

#endif // _GAIJIN_DASCRIPT_MODULES_RAPIDJSON_RAPIDJSONCONFIG_H_
