#ifndef __DENOISER_COMMON_CONSTS_HLSLI__
#define __DENOISER_COMMON_CONSTS_HLSLI__

#define CAMERA_ATTACHED_REFLECTION_MATERIAL_ID 1
#define STRAND_MATERIAL_ID 2

#endif // __DENOISER_COMMON_CONSTS_HLSLI__