#ifndef __GAIJIN_CLIPPING_COMMANDS__
#define __GAIJIN_CLIPPING_COMMANDS__
#pragma once

#include <oldEditor/de_cm.h>

// commands
enum
{
  CM_IMPORT = CM_PLUGIN_BASE,
  CM_CLEAR_DAG_LIST,
  CM_COLLISION_SHOW_PROPS,
  CM_COMPILE_CLIPPING,
  CM_COMPILE_GAME_CLIPPING,
  CM_VIEW_DAG_LIST,
  CM_TOOL
};


#endif //__GAIJIN_CLIPPING_COMMANDS__